local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[306] = {
	RELEASE_DATE = "2022/11/28",
	IMPORTANT = {
		["zhCN"] = {
			"ElvUI 最低支持版本变更为 13.06",
			"移除了 [战斗]-[盟约助手] 模块.",
			"移除了 [鼠标提示]-[盟约] 功能.",
			"[鼠标提示] 套装信息变更为巨龙时代第一套套装.",
			"[超级追踪] 由于暴雪的限制, 快速取消标记从鼠标右键调整为鼠标中键.",
			"[进度] 默认追踪化身巨龙牢窟.",
			"[进度] 默认追踪巨龙时代第一赛季传奇钥石地下城.",
			"[进度] 移除暗影国度第四赛季传奇钥石地下城支持.",
		},
		["zhTW"] = {
			"ElvUI 最低支持版本變更為 13.06",
			"移除了 [戰鬥]-[盟約助手] 模組.",
			"移除了 [浮動提示]-[盟約] 功能.",
			"[浮動提示] 套裝信息變更為巨龍崛起第一套套裝.",
			"[超級追蹤] 由於暴雪的限制, 快速取消標記從滑鼠右鍵調整為滑鼠中鍵.",
			"[進度] 默認追蹤洪荒化身牢獄.",
			"[進度] 默認追蹤巨龍崛起第一賽季傳奇鑰石地下城.",
			"[進度] 移除暗影國度第四賽季傳奇鑰石地下城支持.",
		},
		["enUS"] = {
			"ElvUI minimum supported version changed to 13.06",
			"Remove [Combat]-[Covenant Helper] module.",
			"Remove [Tooltip]-[Covenant] feature.",
			"[Tooltip] Tier Set info changed to the first set in Dragonflight.",
			"[Super Tracker] Due to Blizzard's restriction, pin now can be quickly removed by middle button (right button previously).",
			"[Progress] Default tracking Vault of the Incarnates.",
			"[Progress] Default tracking all Dragonflight S1 Mythic+ Dungeons.",
			"[Progress] Remove tracking support of all Shadowlands S4 Mythic+ Dungeons.",
		},
		["koKR"] = {
			"ElvUI minimum supported version changed to 13.06",
			"Remove [Combat]-[Covenant Helper] module.",
			"Remove [Tooltip]-[Covenant] feature.",
			"[Tooltip] Tier Set info changed to the first set in Dragonflight.",
			"[Super Tracker] Due to Blizzard's restriction, pin now can be quickly removed by middle button (right button previously).",
			"[Progress] Default tracking Vault of the Incarnates.",
			"[Progress] Default tracking all Dragonflight S1 Mythic+ Dungeons.",
			"[Progress] Remove tracking support of all Shadowlands S4 Mythic+ Dungeons.",
		},
	},
	NEW = {
		["zhCN"] = {
			"[美化皮肤] 新增了暴雪原生背包的皮肤.",
			"[美化皮肤] 新增了 AdiBags 的皮肤.",
		},
		["zhTW"] = {
			"[美化皮膚] 新增了暴雪原生背包的皮膚.",
			"[美化皮膚] 新增了 AdiBags 的皮膚.",
		},
		["enUS"] = {
			"[Skins] Add the skin for Blizzard bag.",
			"[Skins] Add the skin for AdiBags.",
		},
		["koKR"] = {
			"[Skins] Add the skin for Blizzard bag.",
			"[Skins] Add the skin for AdiBags.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[通告] 去除任务进度现在不会造成污染.",
			"[通告] 修复新钥石无法被通告的问题. 感谢 Urmus",
			"[交接] 修复存在多个任务时不会自动交接的问题.",
			"[移动框体] 现在可以临时移动额外投掷框体了.",
			"[移动框体] 修复一个移动邮箱时可能造成的错误.",
			"[美化皮肤] 修复镜像计时条的皮肤.",
			"[美化皮肤] 修复 Angry Keystones 的皮肤.",
			"[美化皮肤] 更新 Mythic Dungeon Helper 皮肤.",
			"[美化皮肤] 更新 Immersion 皮肤.",
			"[美化皮肤] 更新设定面板皮肤.",
			"[其他] 修复额外绑定按钮功能.",
		},
		["zhTW"] = {
			"[通告] 去除任務進度現在不會造成污染.",
			"[通告] 修復新鑰石無法被通告的問題. 感謝 Urmus",
			"[交接] 修復存在多個任務時不會自動交接的問題.",
			"[移動框架] 現在可以臨時移動額外投擲框架了.",
			"[移動框架] 修復一個移動郵箱時可能造成的錯誤.",
			"[美化皮膚] 修復鏡像計時條的皮膚.",
			"[美化皮膚] 修復 Angry Keystones 的皮膚.",
			"[美化皮膚] 更新 Mythic Dungeon Helper 皮膚.",
			"[美化皮膚] 更新 Immersion 皮膚.",
			"[美化皮膚] 更新設定介面皮膚.",
			"[其他] 修復額外綁定按鍵功能.",
		},
		["enUS"] = {
			"[Announcement] Remove quest progress will not cause taint now.",
			"[Announcement] Fix the issue that new keystone cannot be announced. Thanks Urmus",
			"[Automation] Fix the issue that auto turn in will not work when there are multiple quests.",
			"[Move Frames] Now you can temporarily move the bonus roll frame.",
			"[Move Frames] Fix the error when moving the mailbox.",
			"[Skins] Fix the skin of mirror timer.",
			"[Skins] Fix the skin of Angry Keystones.",
			"[Skins] Update the skin of Mythic Dungeon Helper.",
			"[Skins] Update the skin of Immersion.",
			"[Skins] Update the skin of Blizzard Settings Panel.",
			"[Misc] Fix the issue that extra binding button not work.",
		},
		["koKR"] = {
			"[Announcement] Remove quest progress will not cause taint now.",
			"[Announcement] Fix the issue that new keystone cannot be announced. Thanks Urmus",
			"[Automation] Fix the issue that auto turn in will not work when there are multiple quests.",
			"[Move Frames] Now you can temporarily move the bonus roll frame.",
			"[Move Frames] Fix the error when moving the mailbox.",
			"[Skins] Fix the skin of mirror timer.",
			"[Skins] Fix the skin of Angry Keystones.",
			"[Skins] Update the skin of Mythic Dungeon Helper.",
			"[Skins] Update the skin of Immersion.",
			"[Skins] Update the skin of Blizzard Settings Panel.",
			"[Misc] Fix the issue that extra binding button not work.",
		},
	},
}
