local W = unpack((select(2, ...)))

W.Changelog[316] = {
	RELEASE_DATE = "2022/12/25",
	IMPORTANT = {
		["zhCN"] = {
			"圣诞快乐!",
			"使用新版 BigWigs API 完全重写了 BigWigs 皮肤. 你现在需要手动在 BigWigs 设定中启用 Wind 工具箱皮肤.",
			"[美化皮肤] 新增了对 BigWigs 计时条, 进本计时条美化的自定义功能.",
			"[通告] 告別和感谢现在默认为关闭状态. 如果你想继续保持礼貌, 手动开启并使用自定义的文本更加能彰显你的独特风格.",
		},
		["zhTW"] = {
			"耶誕節快樂!",
			"使用新版 BigWigs API 完全重寫了 BigWigs 皮膚. 你現在需要手動在 BigWigs 設定中啟用 Wind 工具箱皮膚.",
			"[美化皮膚] 新增了對 BigWigs 計時條, 進本計時條美化的自定義功能.",
			"[通告] 告別和感謝現在默認為關閉狀態. 如果你想繼續保持禮貌, 手動開啟並使用自定義的文本更加能彰顯你的獨特風格.",
		},
		["enUS"] = {
			"Merry Christmas!",
			"Rewrite the BigWigs skin with new BigWigs API. You now need to manually enable the WindTools bar style in the BigWigs options.",
			"[Skins] Added custom settings for BigWigs bars, queue timer skin.",
			"[Announcement] goodbye and thanks are now disabled by default. If you want to be a polite guy, manually enable it and use custom text to show your unique style.",
		},
		["koKR"] = {
			"Merry Christmas!",
			"Rewrite the BigWigs skin with new BigWigs API. You now need to manually enable the WindTools bar style in the BigWigs options.",
			"[Skins] Added custom settings for BigWigs bars, queue timer skin.",
			"[Announcement] goodbye and thanks are now disabled by default. If you want to be a polite guy, manually enable it and use custom text to show your unique style.",
		},
	},
	NEW = {
		["zhCN"] = {
			"[美化皮肤] 新增了 Roll 装历史记录框架的美化.",
			"[美化皮肤] 新增了 Roll 装历史记录中结果字体的单独设定.",
			"[美化皮肤] 新增了 ElvUI 投掷框架的美化.",
			"[美化皮肤] 新增了对 BigWigs 计时条的美化.",
		},
		["zhTW"] = {
			"[美化皮膚] 新增了 Roll 裝歷史記錄框架的美化.",
			"[美化皮膚] 新增了 Roll 裝歷史記錄中結果字體的單獨設定.",
			"[美化皮膚] 新增了 ElvUI 投擲框架的美化.",
			"[美化皮膚] 新增了對 BigWigs 計時條的美化.",
		},
		["enUS"] = {
			"[Skins] Add skin for Roll History frame.",
			"[Skins] Add custom settings for Roll History frame.",
			"[Skins] Add skin for ElvUI Loot Roll frame.",
			"[Skins] Add skin for BigWigs bars.",
		},
		["koKR"] = {
			"[Skins] Add skin for Roll History frame.",
			"[Skins] Add custom settings for Roll History frame.",
			"[Skins] Add skin for ElvUI Loot Roll frame.",
			"[Skins] Add skin for BigWigs bars.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[静音] 修复了闷燃之心静音.",
			"[静音] 新增更多巨龙静音文件 ID.",
			"[小地图按钮] 修复了不使用阴影可能造成错误的问题.",
			"[额外物品条] 更新食物列表.",
			"[观察] 附魔数据库更新至 10.0.2.",
			"[美化皮肤] 修复了不使用阴影可能造成 MDT 错误的问题.",
			"[美化皮肤] 更新名望界面皮肤.",
			"[美化皮肤] 更新了预组队列表皮肤.",
			"[高级] 重置功能更新.",
		},
		["zhTW"] = {
			"[靜音] 修復了燃心靜音.",
			"[靜音] 新增更多巨龍靜音檔案 ID.",
			"[小地圖按鍵] 修復了不使用陰影可能造成錯誤的問題.",
			"[額外物品條] 更新食物列表.",
			"[觀察] 附魔數據庫更新至 10.0.2.",
			"[美化皮膚] 修復了不使用陰影可能造成 MDT 錯誤的問題.",
			"[美化皮膚] 更新名望界面皮膚.",
			"[美化皮膚] 更新了預組列表皮膚.",
			"[進階] 重置功能更新.",
		},
		["enUS"] = {
			"[Mute] Fix the mute of Smolderheart.",
			"[Mute] Add more IDs for Dragon sounds.",
			"[Minimap Buttons] Fix an error caused by not using shadows.",
			"[Extra Items Bar] Update food list.",
			"[Inspect] Update enchant database to 10.0.2.",
			"[Skins] Fix an error of MDT skin caused by not using shadows.",
			"[Skins] Update reputation frame skin.",
			"[Skins] Update lfg list skin.",
			"[Advanced] Update reset support.",
		},
		["koKR"] = {
			"[Mute] Fix the mute of Smolderheart.",
			"[Mute] Add more IDs for Dragon sounds.",
			"[Minimap Buttons] Fix an error caused by not using shadows.",
			"[Extra Items Bar] Update food list.",
			"[Inspect] Update enchant database to 10.0.2.",
			"[Skins] Fix an error of MDT skin caused by not using shadows.",
			"[Skins] Update reputation frame skin.",
			"[Skins] Update lfg list skin.",
			"[Advanced] Update reset support.",
		},
	},
}
