local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[371] = {
	RELEASE_DATE = "2024/08/28",
	IMPORTANT = {
		["zhCN"] = {
			"最低支持的 ElvUI 版本已经提升至 13.76。",
			"[额外物品条] 重新整理了各个物品分组的物品 ID。",
			"[额外物品条] 新增了适用于 11.0 的 POTIONTWW，FLASKTWW，RUNETWW，VANTUS，VANTUSTWW，FOODTWW 分组。",
			"[额外物品条] 调整原来的一些武器符文从 UTILITY 到 RUNE，RUNEDF，RUNETWW 分组。",
			"[额外物品条] FOODVENDOR 分组现在只会显示 11.0 的商人售卖食物和饮料。",
			"[额外物品条] PROF 分组现在只会显示 11.0 专业技能提升物品。",
			"引入 LibShowUIPanel-1.0 库，用于尝试解决面板显示导致的污染问题。",
			"代码清理，优化性能。",
		},
		["zhTW"] = {
			"最低支援的 ElvUI 版本已經提升至 13.76。",
			"[額外物品條] 重新整理了各個物品分組的物品 ID。",
			"[額外物品條] 新增了適用於 11.0 的 POTIONTWW，FLASKTWW，RUNETWW，VANTUS，VANTUSTWW，FOODTWW 分組。",
			"[額外物品條] 調整原來的一些武器符文從 UTILITY 到 RUNE，RUNEDF，RUNETWW 分組。",
			"[額外物品條] FOODVENDOR 分組現在只會顯示 11.0 的商人售賣食物和飲料。",
			"[額外物品條] PROF 分組現在只會顯示 11.0 專業技能提升物品。",
			"引入 LibShowUIPanel-1.0 庫，用於嘗試解決面板顯示導致的污染問題。",
			"代碼清理，優化性能。",
		},
		["enUS"] = {
			"The minimum supported ElvUI version has been raised to 13.76.",
			"[Extra Item Bar] Reorganize the item IDs of each item group.",
			"[Extra Item Bar] Add POTIONTWW, FLASKTWW, RUNETWW, VANTUS, VANTUSTWW, FOODTWW groups for 11.0.",
			"[Extra Item Bar] Move some of the weapon runes from UTILITY to RUNE, RUNEDF, RUNETWW groups.",
			"[Extra Item Bar] The FOODVENDOR group will now only show food and drink sold by vendors in 11.0.",
			"[Extra Item Bar] The PROF group will now only show 11.0 professional skill increasing items.",
			"Add LibShowUIPanel-1.0 library to attempt to resolve pollution issues caused by panel display.",
			"Code cleanup, performance optimization.",
		},
		["koKR"] = {
			"최소 지원되는 ElvUI 버전이 13.76로 상향되었습니다.",
			"[아이템 바] 각 아이템 그룹의 아이템 ID를 재정렬했습니다.",
			"[아이템 바] 11.0용 POTIONTWW, FLASKTWW, RUNETWW, VANTUS, VANTUSTWW, FOODTWW 그룹을 추가했습니다.",
			"[아이템 바] 일부 무기 룬을 UTILITY에서 RUNE, RUNEDF, RUNETWW 그룹으로 이동했습니다.",
			"[아이템 바] FOODVENDOR 그룹은 이제 11.0에서 판매되는 음식과 음료만 표시됩니다.",
			"[아이템 바] PROF 그룹은 이제 11.0 전문 기술 향상 아이템만 표시됩니다.",
			"패널 표시로 인한 오염 문제를 해결하기 위해 LibShowUIPanel-1.0 라이브러리를 추가했습니다.",
			"코드 정리, 성능 최적화.",
		},
		["ruRU"] = {
			"Минимальная поддерживаемая версия ElvUI повышена до 13.76.",
			"[Панель дополнительных предметов] Переорганизованы идентификаторы предметов в каждой группе.",
			"[Панель дополнительных предметов] Добавлены группы POTIONTWW, FLASKTWW, RUNETWW, VANTUS, VANTUSTWW, FOODTWW для 11.0.",
			"[Панель дополнительных предметов] Некоторые руны оружия перемещены из UTILITY в группы RUNE, RUNEDF, RUNETWW.",
			"[Панель дополнительных предметов] Группа FOODVENDOR теперь будет отображать только еду и напитки, продаваемые торговцами в 11.0.",
			"[Панель дополнительных предметов] Группа PROF теперь будет отображать только предметы, увеличивающие профессиональные навыки 11.0.",
			"Добавлена библиотека LibShowUIPanel-1.0 для попытки решения проблем загрязнения, вызванных отображением панели.",
			"Очистка кода, оптимизация производительности.",
		},
	},
	NEW = {
		["zhCN"] = {},
		["zhTW"] = {},
		["enUS"] = {},
		["koKR"] = {},
		["ruRU"] = {},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[美化皮肤] 新增了地下堡相关界面的美化皮肤。",
			"[美化皮肤] 调整了英雄天赋选择界面的美化皮肤。",
			"[美化皮肤] 修复了资料片声望界面阴影错位的问题。",
			"[移动框体] 修复了可能导致英雄天赋界面报错的问题。",
			"[移动框体] 新增了地下堡相关界面的移动功能。",
			"[游戏条] 修复了通知提示的颜色显示。",
			"[其他] - [成就自动截图] 继续优化逻辑，以更加稳定和准确地截图。",
			"[额外物品条] 优化了物品分组设定的提示信息，更容易区分不同版本的分组了。",
			"[额外物品条] 在设定中新增了重置按钮，方便单独重置某个条的分组设定。",
		},
		["zhTW"] = {
			"[美化皮膚] 新增了探究相關介面的美化皮膚。",
			"[美化皮膚] 調整了英雄天賦選擇介面的美化皮膚。",
			"[美化皮膚] 修復了資料片聲望介面陰影錯位的問題。",
			"[移動框體] 修復了可能導致英雄天賦介面報錯的問題。",
			"[移動框體] 新增了探究相關介面的移動功能。",
			"[遊戲條] 修復了通知提示的顏色顯示。",
			"[其他] - [成就自動截圖] 繼續優化邏輯，以更加穩定和準確地截圖。",
			"[額外物品條] 優化了物品分組設定的提示信息，更容易區分不同版本的分組了。",
			"[額外物品條] 在設定中新增了重置按鈕，方便單獨重置某個條的分組設定。",
		},
		["enUS"] = {
			"[Skin] Add skins for Delves UIs.",
			"[Skin] Adjust the skin of the Hero Talent selection interface.",
			"[Skin] Fix the shadow misalignment issue in the expansion landing page.",
			"[Move Frame] Fix an issue that could cause errors in the Hero Talent interface.",
			"[Move Frame] Add the ability to move Delves UIs.",
			"[Game Bar] Fix the color display of notification prompts.",
			"[Misc] - [Auto Screenshot] Optimize the logic for more stable and accurate screenshots.",
			"[Extra Item Bar] Optimize the tooltip of group settings, making it easier to distinguish between different versions of WoW.",
			"[Extra Item Bar] Add a reset button in the settings to easily reset the group settings of a single bar.",
		},
		["koKR"] = {
			"[스킨] 델브 UI용 스킨 추가.",
			"[스킨] 영웅 특성 선택 인터페이스의 스킨을 조정했습니다.",
			"[스킨] 확장팩 랜딩 페이지의 그림자 정렬 문제를 수정했습니다.",
			"[프레임 이동] 영웅 특성 인터페이스에서 오류를 일으킬 수 있는 문제를 수정했습니다.",
			"[프레임 이동] 델브 UI를 이동할 수 있는 기능을 추가했습니다.",
			"[게임 바] 알림 프롬프트의 색상 표시를 수정했습니다.",
			"[기타] - [자동 스크린샷] 더 안정적이고 정확한 스크린샷을 위해 로직을 최적화했습니다.",
			"[추가 아이템 바] 그룹 설정의 툴팁을 최적화하여 WoW의 다른 버전을 쉽게 구분할 수 있도록 했습니다.",
			"[추가 아이템 바] 설정에 재설정 버튼을 추가하여 단일 바의 그룹 설정을 쉽게 재설정할 수 있도록 했습니다.",
		},
		["ruRU"] = {
			"[Скин] Добавлены скины для интерфейсов Подземелий.",
			"[Скин] Изменен скин интерфейса выбора героических талантов.",
			"[Скин] Исправлена проблема с смещением тени на странице расширения.",
			"[Перемещение фрейма] Исправлена проблема, которая могла вызвать ошибки в интерфейсе героических талантов.",
			"[Перемещение фрейма] Добавлена возможность перемещения интерфейсов Подземелий.",
			"[Игровая панель] Исправлено отображение цвета уведомлений.",
			"[Разное] - [Автоматический скриншот] Оптимизирована логика для более стабильных и точных скриншотов.",
			"[Дополнительная панель предметов] Оптимизирована подсказка настроек группы, что делает проще различать разные версии WoW.",
			"[Дополнительная панель предметов] Добавлена кнопка сброса в настройках для легкого сброса настроек группы одной панели.",
		},
	},
}
