local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[398] = {
	RELEASE_DATE = "2025/08/27",
	IMPORTANT = {
		["zhCN"] = {},
		["zhTW"] = {},
		["enUS"] = {},
		["koKR"] = {},
		["ruRU"] = {},
	},
	NEW = {
		["zhCN"] = {
			"[事件追踪器] 新增了夜幕激斗事件.",
			"[事件追踪器] 新增了生态演替周常.",
			"[预组队列表] 右侧面板新增了快速跳转的按钮.",
			"[美化皮肤] 新增了 UI 错误框架的字体颜色替换功能.",
			"[美化皮肤] 新增了 SilverDragon 美化外观. 感谢 Dack",
			"[美化皮肤] 新增了 Talent Loadouts Ex 美化外观. 感谢 NDui_Plus",
			"[美化皮肤] 新增了 Mount Route Planner 美化外观.",
		},
		["zhTW"] = {
			"[事件追蹤器] 新增了夜幕激戰事件.",
			"[事件追蹤器] 新增了生態重構週常.",
			"[預組隊列表] 右側面板新增了快速跳轉的按鈕.",
			"[美化皮膚] 新增了 UI 錯誤框架的字體顏色替換功能.",
			"[美化皮膚] 新增了 SilverDragon 美化外觀. 感謝 Dack",
			"[美化皮膚] 新增了 Talent Loadouts Ex 美化外觀. 感謝 NDui_Plus",
			"[美化皮膚] 新增了 Mount Route Planner 美化外觀.",
		},
		["enUS"] = {
			"[Event Tracker] Add the Nightfall event.",
			"[Event Tracker] Add the Ecological Succession weekly event.",
			"[LFG List] Add a quick access button to the right panel.",
			"[Skins] Add a font color replacement feature for the UI Errors frame.",
			"[Skins] Add SilverDragon skin. Thanks Dack.",
			"[Skins] Add Talent Loadouts Ex skin.",
			"[Skins] Add Mount Route Planner skin.",
		},
		["koKR"] = {
			"[이벤트 추적] 새로운 야경 전투 이벤트 추가.",
			"[이벤트 추적] 새로운 생태계 계승 주간 이벤트 추가.",
			"[LFG 목록] 오른쪽 패널에 빠른 액세스 버튼 추가.",
			"[스킨] UI 오류 프레임의 글꼴 색상 교체 기능 추가.",
			"[스킨] SilverDragon 외관 추가. Dack에게 감사드립니다.",
			"[스킨] Talent Loadouts Ex 외관 추가. NDui_Plus에게 감사드립니다.",
			"[스킨] Mount Route Planner 외관 추가.",
		},
		["ruRU"] = {
			"[Отслеживание событий] Добавлено событие 'Сумерки'.",
			"[Отслеживание событий] Добавлено еженедельное событие 'Экологическая сукцессия'.",
			"[Список LFG] Добавлена кнопка быстрого доступа на правой панели.",
			"[Скины] Добавлена функция замены цвета шрифта для фрейма ошибок интерфейса.",
			"[Скины] Добавлен скин для SilverDragon. Спасибо Dack.",
			"[Скины] Добавлен скин для Talent Loadouts Ex. Спасибо NDui_Plus.",
			"[Скины] Добавлен скин для Mount Route Planner.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[美化皮肤] 优化 OmniCD 外观.",
			"[美化皮肤] 优化 BtWQuests 外观.",
			"[美化皮肤] 优化试衣间外观.",
			"[美化皮肤] 优化任务界面外观.",
			"[美化皮肤] 优化鼠标提示的外观, 现在会自动美化全部的鼠标提示内图标.",
			"[小地图按钮] 修正了资料片按钮点击区域过小的问题.",
			"[小地图按钮] 优化了静思助手的按钮处理逻辑.",
			"[小地图按钮] 优化了 Mount Route Planner 的按钮处理逻辑.",
			"[其他] - [跳过过场动画] 在选择'仅观看过的'时, 如果过场动画ID无法确定, 现在则不会跳过.",
			"[退出相位潜行] 稍微更新了按钮的外观.",
		},
		["zhTW"] = {
			"[美化外觀] 優化 OmniCD 外觀.",
			"[美化外觀] 優化 BtWQuests 外觀.",
			"[美化外觀] 優化試衣間外觀.",
			"[美化外觀] 優化任務界面外觀.",
			"[美化外觀] 優化浮動提示的外觀, 現在會自動美化全部的浮動提示內圖示.",
			"[小地圖按鍵] 修正了資料片按鍵點擊區域過小的問題.",
			"[小地圖按鍵] 優化了靜思助手的按鍵處理邏輯.",
			"[小地圖按鍵] 優化了 Mount Route Planner 的按鍵處理邏輯.",
			"[其他] - [跳過過場動畫] 在選擇'僅觀看過的'時, 如果過場動畫ID無法確定, 現在則不會跳過.",
			"[退出相位深潛] 稍微更新了按鍵的外觀.",
		},
		["enUS"] = {
			"[Skins] Optimize OmniCD skin.",
			"[Skins] Optimize BtWQuests skin.",
			"[Skins] Optimize Dressing Room skin.",
			"[Skins] Optimize Quest skin.",
			"[Skins] Optimize Tooltip skin. Now it automatically beautifies all icons within tooltips.",
			"[Minimap Buttons] Fix the issue with the small click area of the expansion button.",
			"[Minimap Buttons] Optimize the button handling logic of Jingsi Tools.",
			"[Minimap Buttons] Optimize the button handling logic of Mount Route Planner.",
			"[Misc] - [Skip Cut Scene] When 'Only Watched' is selected, if the cutscene ID cannot be determined, it will not be skipped now.",
			"[Exit Phase Diving] Update the appearance of the button a little bit.",
		},
		["koKR"] = {
			"[스킨] OmniCD 외관 최적화.",
			"[스킨] BtWQuests 외관 최적화.",
			"[스킨] 드레싱룸 외관 최적화.",
			"[스킨] 퀘스트 외관 최적화.",
			"[스킨] 툴팁 외관 최적화. 이제 툴팁 내 모든 아이콘이 자동으로 미화됩니다.",
			"[미니맵 버튼] 확장 버튼 클릭 영역이 너무 작았던 문제 수정.",
			"[미니맵 버튼] 정수 도구의 버튼 처리 논리 최적화.",
			"[미니맵 버튼] Mount Route Planner의 버튼 처리 논리 최적화.",
			"[기타] - [컷신 건너뛰기] '단지 시청한'이 선택되면 컷신 ID를 확인할 수 없는 경우 이제 건너뛰지 않습니다.",
			"[잠수 중 탈출] 버튼의 외관을 약간 업데이트했습니다.",
		},
		["ruRU"] = {
			"[Скины] Оптимизирован внешний вид OmniCD.",
			"[Скины] Оптимизирован внешний вид BtWQuests.",
			"[Скины] Оптимизирован внешний вид примерочной.",
			"[Скины] Оптимизирован внешний вид интерфейса квестов.",
			"[Скины] Оптимизирован внешний вид подсказок. Теперь они автоматически улучшают все значки внутри подсказок.",
			"[Кнопки миникарты] Исправлена проблема с маленькой областью нажатия кнопки расширения.",
			"[Кнопки миникарты] Оптимизирована логика обработки кнопок Jingsi Tools.",
			"[Кнопки миникарты] Оптимизирована логика обработки кнопок Mount Route Planner.",
			"[Прочее] - [Пропустить кат-сцену] Если выбрано 'Только просмотренные', и ID кат-сцены не может быть определен, она больше не будет пропущена.",
			"[Выход из фазового погружения] Обновлен внешний вид кнопки.",
		},
	},
}
