local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[399] = {
	RELEASE_DATE = "TBD",
	IMPORTANT = {
		["zhCN"] = {
			"大量的过期代码整理.",
			"优化了一些内部函数的性能.",
			"重构了对第三方函数库美化的核心逻辑.",
			"由于暴雪已经修复相关 Bug, 移除对地下堡部分事件的节流处理.",
			"优化了韩语翻译文本. 感谢 Crazyyoungs",
		},
		["zhTW"] = {
			"大量的過期代碼整理.",
			"優化了一些內部函式的性能.",
			"重構了對第三方函式庫美化的核心邏輯.",
			"由於暴雪已經修復相關 Bug, 移除對探究部分事件的節流處理.",
			"優化了韓文翻譯文本. 感謝 Crazyyoungs",
		},
		["enUS"] = {
			"Massive cleanup of deprecated code.",
			"Optimize the performance of some internal functions.",
			"Refactor the core logic for third-party library skinning.",
			"Remove throttling for some Delves events since Blizzard has fixed the related bugs.",
			"Optimize Korean translation text. Thanks Crazyyoungs.",
		},
		["koKR"] = {
			"대량의 사용되지 않는 코드를 정리했습니다.",
			"일부 내부 함수의 성능을 최적화했습니다.",
			"서드파티 라이브러리 외관의 핵심 로직을 리팩터링했습니다.",
			"블리자드에서 관련 버그를 수정했으므로 지하 던전 일부 이벤트의 제한 처리를 제거했습니다.",
			"한국어 번역 텍스트를 최적화했습니다. Crazyyoungs에게 감사드립니다.",
		},
		["ruRU"] = {
			"Массовая очистка устаревшего кода.",
			"Оптимизирована производительность некоторых внутренних функций.",
			"Рефакторинг основной логики для стилизации сторонних библиотек.",
			"Удалено ограничение для некоторых событий подземелий, поскольку Blizzard исправила связанные ошибки.",
			"Оптимизирован текст перевода на корейский. Спасибо Crazyyoungs.",
		},
	},
	NEW = {
		["zhCN"] = {
			"[美化皮肤] 新增了暴雪区域地图的美化外观.",
			"[美化皮肤] 新增了 WhisperPop 美化外观. 感谢 DaguDuiyuan",
			"[美化皮肤] 新增了 Paragon Reputation 美化外观.",
			"[美化皮肤] 新增了 Manuscripts Journal 美化外观.",
		},
		["zhTW"] = {
			"[美化皮膚] 新增了暴雪區域地圖的美化外觀.",
			"[美化皮膚] 新增了 WhisperPop 美化外觀. 感謝 DaguDuiyuan",
			"[美化皮膚] 新增了 Paragon Reputation 美化外觀.",
			"[美化皮膚] 新增了 Manuscripts Journal 美化外觀.",
		},
		["enUS"] = {
			"[Skins] Add Blizzard Battlefield Map skin.",
			"[Skins] Add WhisperPop skin. Thanks DaguDuiyuan.",
			"[Skins] Add Paragon Reputation skin.",
			"[Skins] Add Manuscripts Journal skin.",
		},
		["koKR"] = {
			"[스킨] 블리자드 전장 지도 외관 추가.",
			"[스킨] WhisperPop 외관 추가. DaguDuiyuan에게 감사드립니다.",
			"[스킨] Paragon Reputation 외관 추가.",
			"[스킨] Manuscripts Journal 외관 추가.",
		},
		["ruRU"] = {
			"[Скины] Добавлен скин для карты поля боя Blizzard.",
			"[Скины] Добавлен скин для WhisperPop. Спасибо DaguDuiyuan.",
			"[Скины] Добавлен скин для Paragon Reputation.",
			"[Скины] Добавлен скин для Manuscripts Journal.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"优化了插件内全部聊天链接的处理逻辑.",
			"修复了启用高级战斗事件追踪时可能出现的错误.",
			"[美化皮肤] 现在在不载入插件时也能够开关对应皮肤了.",
			"[美化皮肤] ElvUI 职业条皮肤新增对额外能量条的支持.",
			"[美化皮肤] 优化商人界面中的图示美化.",
			"[美化皮肤] 优化盟约名望界面中的按钮美化.",
			"[美化皮肤] 优化任务线玩家选择界面外观.",
			"[美化皮肤] 优化 WeakAuras 性能分析界面外观.",
			"[美化皮肤] 优化 Simulationcraft 外观.",
			"[美化皮肤] 优化 Mythic Dungeon Tools 拉怪波次按钮外观.",
			"[美化皮肤] 优化 SilverDragon 皮肤的一些逻辑, 现在能够更加快速的捕获窗口执行美化.",
			"[美化皮肤] 修复了 World Quest Tab 皮肤可能造成的错误.",
			"[美化皮肤] 修复了树状分组按钮组件皮肤有时背景过淡的问题.",
			"[美化皮肤] 优化了有时 Ace3 鼠标提示无法在初次显示时自动美化的问题.",
			"[扩展商人界面] 现在和其他已知的同类插件混用时的会自动停用.",
			"[扩展商人界面] 优化了购回按钮的位置.",
			"[游戏条] 优化了一些错误提示, 使其更加贴合系统错误的风格.",
			"[游戏条] 时间部分新增一个选项, 可以防止在战斗中误触导致界面重载.",
			"[游戏条] 重构了随机炉石功能，现在支持盟约炉石的使用, 同时点击按钮后立即更换下一个不同的炉石.",
			"[预组队列表] 右侧面板新增了字体大小调整的功能.",
			"[预组队列表] 修复举报有时候无法使用的污染. 感谢 Dack",
			"[世界地图] 修复了区域地图的去除迷雾功能.",
			"[小地图按钮] 增强了对使用 LibDBIcon 插件的图标自动美化.",
			"[小地图按钮] 重构了版本大厅按钮的处理逻辑.",
			"[额外物品条] 新增了一些可开启物品.",
			"[任务列表] 重写了模块, 现在能更快更好地处理自定义外观了.",
			"[鼠标提示] 优化图标切割逻辑, 能够识别更多需要切割的图标.",
			"[技能激活提醒] 模块重构, 并同时修复了设定预览功能.",
		},
		["zhTW"] = {
			"優化了插件內全部聊天連結的處理邏輯.",
			"修復了啟用進階戰鬥事件追蹤時可能出現的錯誤.",
			"[美化外觀] 現在在不載入插件時也能夠開關對應外觀了.",
			"[美化外觀] ElvUI 職業條外觀新增對額外能量條的支援.",
			"[美化外觀] 優化商人介面中的圖示美化.",
			"[美化外觀] 優化誓盟名望介面中的按鈕美化.",
			"[美化外觀] 優化任務線玩家選擇介面外觀.",
			"[美化外觀] 優化 WeakAuras 性能分析介面外觀.",
			"[美化外觀] 優化 Simulationcraft 外觀.",
			"[美化外觀] 優化 Mythic Dungeon Tools 拉怪波次按鍵外觀.",
			"[美化外觀] 優化 SilverDragon 外觀的一些邏輯, 現在能夠更加快速的捕獲視窗執行美化.",
			"[美化外觀] 修復了 World Quest Tab 外觀可能造成的錯誤.",
			"[美化外觀] 修復了樹狀分組按鍵組件外觀有時背景過淡的問題.",
			"[美化外觀] 優化了有時 Ace3 浮動提示無法在初次顯示時自動美化的問題.",
			"[擴展商人頁面] 現在和其他已知的同類插件混用時的會自動停用.",
			"[擴展商人頁面] 優化了購回按鈕的位置.",
			"[遊戲條] 優化了一些錯誤提示, 使其更加貼合系統錯誤的風格.",
			"[遊戲條] 時間部分新增一個選項, 可以防止在戰鬥中誤觸導致介面重載.",
			"[遊戲條] 重構了隨機爐石功能，現在支援誓盟爐石的使用, 同時點擊按鈕後立即更換下一個不同的爐石.",
			"[預組隊列表] 右側面板新增了字型大小調整的功能.",
			"[預組隊列表] 修復舉報有時候無法使用的污染. 感謝 Dack",
			"[世界地圖] 修復了區域地圖的去除迷霧功能.",
			"[小地圖按鍵] 增強了對使用 LibDBIcon 插件的圖示自動美化.",
			"[小地圖按鍵] 重構了版本大廳按鈕的處理邏輯.",
			"[額外物品條] 新增了一些可開啟物品.",
			"[任務列表] 重寫了模組, 現在能更快更好地處理自訂外觀了.",
			"[滑鼠提示] 優化圖示切割邏輯, 能夠識別更多需要切割的圖示.",
			"[技能激活提醒] 模組重構, 並同時修復了設定預覽功能.",
		},
		["enUS"] = {
			"Optimize the handling logic for all chat links within the addon.",
			"Fix errors that could occur when advanced combat event tracking was enabled.",
			"[Skins] Now able to toggle corresponding skins even when addons are not loaded.",
			"[Skins] ElvUI class bar skin now supports additional power bars.",
			"[Skins] Optimize icon skinning in merchant frame.",
			"[Skins] Optimize button skinning in covenant renown frame.",
			"[Skins] Optimize player choice frame skin.",
			"[Skins] Optimize WeakAuras Profiler skin.",
			"[Skins] Optimize Simulationcraft skin.",
			"[Skins] Optimize Mythic Dungeon Tools pull button skin.",
			"[Skins] Optimize some logic of SilverDragon skin, now it can capture windows and apply skinning more quickly.",
			"[Skins] Fix errors that could be caused by World Quest Tab skin.",
			"[Skins] Fix the issue where tree group button component skin sometimes has too light background.",
			"[Skins] Optimize the logic for Ace3 tooltip skinning, ensuring it applies correctly on first display.",
			"[Extend Merchant Pages] Now automatically disables when mixed with other known similar addons.",
			"[Extend Merchant Pages] Optimize the position of buyback button.",
			"[Game Bar] Optimize some error messages to better match the style of system errors.",
			"[Game Bar] Add an option in the time section to prevent accidental triggering of UI reload during combat.",
			"[Game Bar] Refactor the random hearthstone feature, now supports covenant hearthstones and immediately switches to the next different hearthstone after clicking the button.",
			"[LFG List] Add font size adjustment feature to the right panel.",
			"[LFG List] Fix the taint that sometimes prevents reporting from working. Thanks Dack.",
			"[World Map] Fix the reveal feature for the battlefield map.",
			"[Minimap Buttons] Enhance the automatic skinning for addons using LibDBIcon .",
			"[Minimap Buttons] Refactor the handling logic for Expansion Landing Page button.",
			"[Extra Item Bar] Add some openable items.",
			"[Quest List] Rewrite the module, now can handle custom appearance faster and better.",
			"[Tooltip] Optimize icon cropping logic, able to recognize more icons that need cropping.",
			"[Spell Activation Alert] Refactor the module. Fix the preview feature when changing options.",
		},
		["koKR"] = {
			"애드온 내 모든 채팅 링크의 처리 로직을 최적화했습니다.",
			"고급 전투 이벤트 추적이 활성화되었을 때 발생할 수 있는 오류를 수정했습니다.",
			"[스킨] 이제 애드온이 로드되지 않았을 때도 해당 스킨을 켜고 끌 수 있습니다.",
			"[스킨] ElvUI 클래스 바 스킨이 이제 추가 파워 바를 지원합니다.",
			"[스킨] 상인 인터페이스의 아이콘 스킨을 최적화했습니다.",
			"[스킨] 성약 명성 인터페이스의 버튼 스킨을 최적화했습니다.",
			"[스킨] 퀘스트 선택 인터페이스의 아이콘 스킨을 최적화했습니다.",
			"[스킨] WeakAuras 성능 분석 인터페이스 외관을 최적화했습니다.",
			"[스킨] Simulationcraft 외관을 최적화했습니다.",
			"[스킨] Mythic Dungeon Tools 라인업 버튼 외관을 최적화했습니다.",
			"[스킨] SilverDragon 스킨의 일부 로직을 최적화하여 이제 창을 더 빠르게 캡처하고 스킨을 적용할 수 있습니다.",
			"[스킨] World Quest Tab 스킨으로 인해 발생할 수 있는 오류를 수정했습니다.",
			"[스킨] 트리 그룹 버튼 구성 요소 스킨의 배경이 때때로 너무 연한 문제를 수정했습니다.",
			"[스킨] Ace3 툴팁 스킨 처리 로직을 최적화하여 처음 표시될 때 올바르게 적용되도록 했습니다.",
			"[상인 페이지 확장] 이제 다른 알려진 유사한 애드온과 함께 사용할 때 자동으로 비활성화됩니다.",
			"[상인 페이지 확장] 되사기 버튼의 위치를 최적화했습니다.",
			"[게임 바] 일부 오류 메시지를 최적화하여 시스템 오류 스타일에 더 잘 맞도록 했습니다.",
			"[게임 바] 시간 섹션에 전투 중 실수로 UI 재로드를 트리거하는 것을 방지하는 옵션을 추가했습니다.",
			"[게임 바] 랜덤 귀환석 기능을 재구성하여 이제 성약 귀환석을 지원하고 버튼을 클릭한 후 즉시 다음 다른 귀환석으로 전환됩니다.",
			"[LFG 목록] 오른쪽 패널에 글꼴 크기 조정 기능을 추가했습니다.",
			"[LFG 목록] 신고가 때때로 작동하지 않게 하는 오염 문제를 수정했습니다. Dack에게 감사드립니다.",
			"[세계 지도] 전장 지도의 안개 제거 기능을 수정했습니다.",
			"[미니맵 버튼] LibDBIcon을 사용하는 애드온의 자동 스킨 기능을 향상시켰습니다.",
			"[미니맵 버튼] 확장팩 랜딩 페이지 버튼의 처리 로직을 재구성했습니다.",
			"[추가 아이템 바] 일부 열 수 있는 아이템을 추가했습니다.",
			"[퀘스트 목록] 모듈을 다시 작성하여 이제 사용자 정의 외관을 더 빠르고 더 잘 처리할 수 있습니다.",
			"[툴팁] 아이콘 자르기 로직을 최적화하여 자르기가 필요한 더 많은 아이콘을 인식할 수 있습니다.",
			"[스킬 활성화 알림] 모듈을 재구성하고 옵션 변경 시 미리보기 기능을 수정했습니다.",
		},
		["ruRU"] = {
			"Оптимизирована логика обработки всех ссылок чата в аддоне.",
			"Исправлены ошибки, которые могли возникнуть при включенном расширенном отслеживании боевых событий.",
			"[Скины] Теперь можно включать и выключать соответствующие скины даже когда аддоны не загружены.",
			"[Скины] Скин панели классов ElvUI теперь поддерживает дополнительные панели энергии.",
			"[Скины] Оптимизирован скин иконок в интерфейсе торговца.",
			"[Скины] Оптимизирован скин кнопок в интерфейсе репутации ковенантов.",
			"[Скины] Оптимизирован скин иконок в интерфейсе выбора игрока.",
			"[Скины] Оптимизирован внешний вид анализатора производительности WeakAuras.",
			"[Скины] Оптимизирован внешний вид Simulationcraft.",
			"[Скины] Оптимизирован внешний вид Mythic Dungeon Tools.",
			"[Скины] Оптимизирована некоторая логика скина SilverDragon, теперь он может быстрее захватывать окна и применять скины.",
			"[Скины] Исправлены ошибки, которые могли быть вызваны скином World Quest Tab.",
			"[Скины] Исправлена проблема, когда скин компонентов древовидных групповых кнопок иногда имеет слишком светлый фон.",
			"[Скины] Оптимизирована логика обработки скина Ace3, теперь он правильно применяется при первом отображении.",
			"[Расширенные страницы торговца] Теперь автоматически отключается при использовании с другими известными похожими аддонами.",
			"[Расширенные страницы торговца] Оптимизировано положение кнопки выкупа.",
			"[Игровая панель] Оптимизированы некоторые сообщения об ошибках, чтобы лучше соответствовать стилю системных ошибок.",
			"[Игровая панель] Добавлена опция в секции времени для предотвращения случайного запуска перезагрузки UI во время боя.",
			"[Игровая панель] Переработана функция случайного камня возвращения, теперь поддерживает камни ковенантов и сразу переключается на следующий камень после нажатия кнопки.",
			"[LFG список] Добавлена функция изменения размера шрифта для правой панели.",
			"[LFG список] Исправлено загрязнение, которое иногда препятствует работе отчетности. Спасибо Dack.",
			"[Мировая карта] Исправлена функция раскрытия для карты поля боя.",
			"[Кнопки миникарты] Улучшена автоматическая стилизация для аддонов, использующих LibDBIcon.",
			"[Кнопки миникарты] Переработана логика обработки кнопки Landing Page расширения.",
			"[Дополнительная панель предметов] Добавлены некоторые открываемые предметы.",
			"[Список заданий] Переписан модуль, теперь может быстрее и лучше обрабатывать пользовательский внешний вид.",
			"[Подсказка] Оптимизирована логика обрезки иконок, теперь может распознавать больше иконок, требующих обрезки.",
			"[Оповещение об активации заклинания] Модуль был переработан, и функция предварительного просмотра была исправлена при изменении параметров.",
		},
	},
}
