local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[401] = {
	RELEASE_DATE = "TBD",
	IMPORTANT = {
		["zhCN"] = {
			"进行了一些核心代码的重构, 提升了稳定性和性能.",
		},
		["zhTW"] = {
			"進行了一些核心代碼的重構, 提升了穩定性和效能.",
		},
		["enUS"] = {
			"Some core code has been refactored to improve stability and performance.",
		},
		["koKR"] = {
			"안정성과 성능을 향상시키기 위해 일부 핵심 코드가 리팩토링되었습니다.",
		},
		["ruRU"] = {
			"Некоторый основной код был переработан для повышения стабильности и производительности.",
		},
	},
	NEW = {
		["zhCN"] = {
			"[美化外观] 新增了 Collectionator 皮肤.",
			"[美化外观] 新增了 Plumber 皮肤.",
			"[美化外观] 新增了 TomTom 皮肤.",
			"[美化外观] 新增了 Legion Remix Helper 皮肤.",
			"[小地图按钮] 新增了根据按钮名优先度排序功能.",
		},
		["zhTW"] = {
			"[美化外觀] 新增了 Collectionator 皮膚.",
			"[美化外觀] 新增了 Plumber 皮膚.",
			"[美化外觀] 新增了 TomTom 皮膚.",
			"[小地圖按鈕] 新增了根據按鍵名優先度排序功能.",
		},
		["enUS"] = {
			"[Skins] Add skin for Collectionator.",
			"[Skins] Add skin for Plumber.",
			"[Skins] Add skin for TomTom.",
			"[Minimap Buttons] Add function to sort by button name priority.",
		},
		["koKR"] = {
			"[스킨] Collectionator에 스킨이 추가되었습니다.",
			"[스킨] Plumber에 스킨이 추가되었습니다.",
			"[스킨] TomTom에 스킨이 추가되었습니다.",
			"[미니맵 버튼] 버튼 이름 우선순위로 정렬하는 기능이 추가되었습니다.",
		},
		["ruRU"] = {
			"[Скины] Добавлен скин для Collectionator.",
			"[Скины] Добавлен скин для Plumber.",
			"[Скины] Добавлен скин для TomTom.",
			"[Кнопки миникарты] Добавлена функция сортировки по приоритету имени кнопки.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[美化外观] 优化了 Auctionator 的皮肤.",
			"[美化外观] 优化了冒险地图皮肤.",
			"[美化外观] 优化好友界面中近期往来的皮肤.",
			"[美化外观] 优化了一些UI组件中的文字显示.",
			"[小地图按钮] 增强了对部分按钮的支持.",
			"[战斗提示] 重构了模组，提升性能.",
			"[预组建队伍] 新增了军团Remix的史诗钥石地下城的支持.",
			"[预组建队伍] 修复了队长地下城分数无法正常排序的问题.",
			"[好友列表] 支持了好友界面中近期往来界面.",
			"[通告] - [任务] 移除暴雪选项开启时，现在的暴雪任务进度将会被清除得更加干净（无空行产生）.",
		},
		["zhTW"] = {
			"[美化外觀] 優化了 Auctionator 的皮膚.",
			"[美化外觀] 優化了 SilverDragon 的皮膚.",
			"[美化外觀] 優化了冒險地圖皮膚.",
			"[美化外觀] 優化了好友介面中近期往來的皮膚.",
			"[戰鬥提示] 重構了模組，提升效能.",
			"[小地圖按鈕] 增強了對部分按鈕的支援.",
			"[預組隊伍] 新增了軍團Remix的傳奇鑰石地城的支援.",
			"[預組隊伍] 修復了隊長地下城分數無法正常排序的問題.",
			"[好友列表] 支援了好友介面中近期盟友介面.",
			"[通告] - [任務] 移除暴雪選項開啟時，現在的暴雪任務進度將會被清除得更加乾淨（無空行產生）.",
		},
		["enUS"] = {
			"[Skins] Update Auctionator skin.",
			"[Skins] Update SilverDragon skin.",
			"[Skins] Update Adventure Map skin.",
			"[Skins] Update Friend List skin, especially Recent Allies section.",
			"[Combat Alert] Refactor the module for better performance.",
			"[Minimap Buttons] Improve support for some buttons.",
			"[LFG List] Add support for Legion Remix Mythic+.",
			"[Friend List] Support Recent Allies section in Friend List.",
			"[Announcements] - [Quests] When 'Remove Blizzard' is enabled, the current Blizzard quest progress will now be cleaned up more thoroughly (no empty lines).",
		},
		["koKR"] = {
			"[스킨] Auctionator 스킨이 업데이트되었습니다.",
			"[스킨] SilverDragon 스킨이 업데이트되었습니다.",
			"[스킨] 어드벤처 맵 스킨이 업데이트되었습니다.",
			"[스킨] 친구 목록 스킨, 특히 최근 동맹 섹션이 업데이트되었습니다.",
			"[전투 알림] 더 나은 성능을 위해 모듈이 리팩토링되었습니다.",
			"[미니맵 버튼] 일부 버튼에 대한 지원이 개선되었습니다.",
			"[파티 찾기 목록] 군단 리믹스 신화+ 지원이 추가되었습니다.",
			"[파티 찾기 목록] 수정된 던전 점수가 올바르게 정렬되지 않는 문제를 해결했습니다.",
			"[친구 목록] 친구 목록에서 최근 동맹 섹션을 지원합니다.",
			"[공지사항] - [퀘스트] '블리자드 제거'가 활성화되면 현재 블리자드 퀘스트 진행 상황이 더 철저하게 정리됩니다(빈 줄 없음).",
		},
		["ruRU"] = {
			"[Скины] Обновлен скин Auctionator.",
			"[Скины] Обновлен скин SilverDragon.",
			"[Скины] Обновлен скин карты приключений.",
			"[Скины] Обновлен скин списка друзей, особенно раздел 'Недавние союзники'.",
			"[Боевые оповещения] Модуль переработан для повышения производительности.",
			"[Кнопки миникарты] Улучшена поддержка некоторых кнопок.",
			"[Список поиска групп] Добавлена поддержка Легиона Remix Mythic+.",
			"[Список поиска групп] Исправлена ошибка сортировки очков подземелий для лидеров группы.",
			"[Список друзей] Поддержка раздела 'Недавние союзники' в списке друзей.",
			"[Объявления] - [Задания] Когда включена опция 'Удалить Blizzard', текущий прогресс заданий Blizzard теперь будет очищаться более тщательно (без пустых строк).",
		},
	},
}
