local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[402] = {
	RELEASE_DATE = "TBD",
	IMPORTANT = {
		["zhCN"] = {
			"清理代码, 移除一些过时的功能和函数.",
			"优化了韩语翻译. 感谢 Crazyyoungs",
			"修复了队伍组成变化时可能产生的 '不在队伍中' 错误提示问题.",
			"库文件更新. 现在能够更好的和 BigWigs 及 Details 互相交换钥石信息.",
			"[高级] - [重置] 修复了某些情况下无法正确重置配置的问题.",
			"[通告] - [任务] 中的任务信息功能现在分离为了一个独立模块 [任务] - [进度].",
		},
		["zhTW"] = {
			"清理代碼, 移除一些過時的功能和函數.",
			"優化了韓語翻譯. 感謝 Crazyyoungs",
			"修復了隊伍組成變化時可能產生的 '不在隊伍中' 錯誤提示問題.",
			"庫文件更新. 現在能夠更好的和 BigWigs 及 Details 互相交換鑰石信息.",
			"[進階] - [重置] 修復了某些情況下無法正確重置配置的問題.",
			"[通告] - [任務] 中的任務信息功能現在分離為了一個獨立模組 [任務] - [進度].",
		},
		["enUS"] = {
			"Cleaned up code, removed some outdated features and functions.",
			"Optimize Korean translation. Thanks to Crazyyoungs",
			"Fix issue where 'not in a party' error message may appear when party composition changes.",
			"Library files updated. Now better exchange keystone information with BigWigs and Details.",
			"[Advanced] - [Reset] Fix issue where configuration may not reset correctly in some cases.",
			"The colored quest progress info feature from [Announcements] - [Quest] is now separated into an independent module [Quests] - [Progress].",
		},
		["koKR"] = {
			"코드 정리, 일부 오래된 기능 및 함수 제거.",
			"한국어 번역을 최적화했습니다. Crazyyoungs에게 감사합니다",
			"파티 구성 변경 시 '파티에 없음' 오류 메시지가 나타날 수 있는 문제를 수정했습니다.",
			"라이브러리 파일이 업데이트되었습니다. 이제 BigWigs 및 Details와 더 나은 열쇠 정보 교환이 가능합니다.",
			"[고급] - [재설정] 일부 경우에 구성이 올바르게 재설정되지 않을 수 있는 문제를 수정했습니다.",
			"[공지사항] - [퀘스트]의 퀘스트 정보 기능이 독립 모듈 [퀘스트] - [진행 상황]으로 분리되었습니다.",
		},
		["ruRU"] = {
			"Очистка кода, удаление некоторых устаревших функций и методов.",
			"Оптимизирован перевод на корейский язык. Спасибо Crazyyoungs",
			"Исправлена проблема, из-за которой при изменении состава группы могло появляться сообщение об ошибке 'не в группе'.",
			"Обновлены файлы библиотеки. Теперь обмен информацией о ключах М+ с BigWigs и Details стал ещё лучше.",
			"[Дополнительно] - [Сброс] Исправлена проблема, из-за которой конфигурация могла не сбрасываться правильно в некоторых случаях.",
			"Функция цветной информации о прогрессе заданий из [Объявления] - [Задания] теперь выделена в независимый модуль [Задания] - [Прогресс].",
		},
	},
	NEW = {
		["zhCN"] = {
			"新增模块: [任务] - [进度]. 增强任务进度信息内容的同时, 支持模板化和自定义渐变色.",
			"[美化外观] 新增了暴雪冷却技能监控的美化设定页. 支持修改图标的比例, 文字, 材质等.",
			"[美化外观] 新增了新暴雪商店美化. (ElvUI 版本 14.03 开发版及以上支持此功能)",
			"[任务列表] 新增文字风格选项, 可设定文字是否强制在单行内显示 (超出部分缩写为 ...).",
			"[单位框体] - [职责图标] 新增了暴雪风格的图标组.",
			"[单位框体] - [快速焦点] 新增了焦点时设定团队标记的功能, 默认关闭.",
		},
		["zhTW"] = {
			"新增模組: [任務] - [進度]. 增強任務進度信息內容的同時, 支援模板化和自訂漸變色.",
			"[美化外觀] 新增了暴雪冷卻技能監控的美化設定頁. 支援修改圖示的比例, 文字, 材質等.",
			"[美化外觀] 新增了新暴雪商店美化. (ElvUI 版本 14.03 開發版及以上支援此功能)",
			"[任務列表] 新增文字風格選項, 可設定文字是否強制在單行內顯示 (超出部分縮寫為 ...).",
			"[單位框架] - [職責圖示] 新增了暴雪風格的圖示組.",
			"[單位框架] - [快速焦點] 新增了焦點時設定團隊標記的功能, 預設關閉.",
		},
		["enUS"] = {
			"New Module: [Quests] - [Progress]. Enhances quest progress info content while supporting templating and custom gradients.",
			"[Skins] Add separate styling options tab for Blizzard Cooldown Viewer. Supports modifying icon ratio, text, textures, etc.",
			"[Skins] Add styling for the new Blizzard Catalog Shop. (Supported in ElvUI version 14.03 Dev and above)",
			"[Objective Tracker] New text style option to set whether text is forced to display in a single line (exceeding part abbreviated as ...).",
			"[Unit Frames] - [Role Icons] Added Blizzard style icon set.",
			"[Unit Frames] - [Quick Focus] Added option to set raid marker when focusing, disabled by default.",
		},
		["koKR"] = {
			"새로운 모듈: [퀘스트] - [진행 상황]. 퀘스트 진행 상황 정보 콘텐츠를 향상시키면서 템플릿화 및 사용자 지정 그라데이션을 지원합니다.",
			"[스킨] 블리자드 쿨다운 뷰어를 위한 별도의 스타일링 옵션 탭을 추가했습니다. 아이콘 비율, 텍스트, 텍스처 등을 수정하는 것을 지원합니다.",
			"[스킨] 새로운 블리자드 카탈로그 상점을 위한 스타일링을 추가했습니다. (ElvUI 버전 14.03 개발 버전 이상에서 지원됨)",
			"[퀘스트 추적기] 텍스트가 단일 행에 표시되도록 강제할지 여부를 설정하는 새로운 텍스트 스타일 옵션 (초과 부분은 ...로 축약됨).",
			"[유닛 프레임] - [역할 아이콘] 블리자드 스타일 아이콘 세트를 추가했습니다.",
			"[유닛 프레임] - [빠른 집중] 집중할 때 공격대 표시기를 설정하는 옵션을 추가했으며 기본적으로 비활성화되어 있습니다.",
		},
		["ruRU"] = {
			"Новый модуль: [Задания] - [Прогресс]. Улучшает содержимое информации о прогрессе заданий, поддерживая шаблоны и пользовательские градиенты.",
			"[Скины] Добавлена отдельная вкладка параметров стилизации для Трекера Восстановлений Blizzard. Поддерживает изменение соотношения иконок, текста, текстур и т.д.",
			"[Скины] Добавлена стилизация для нового магазина Blizzard. (Поддерживается в версии ElvUI 14.03 Dev и выше)",
			"[Список заданий] Новая опция стиля текста для установки того, отображается ли текст в одной строке (превышающая часть сокращается как ...).",
			"[Юнит-фреймы] - [Иконки ролей] Добавлен набор иконок в стиле Blizzard.",
			"[Юнит-фреймы] - [Быстрый фокус] Добавлена опция установки рейдовой метки при фокусировке, по умолчанию отключена.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[美化外观] 优化了场景中的法术按钮.",
			"[美化外观] 优化了新建天赋配置的界面.",
			"[美化外观] 修复了 Rematch 皮肤在独立模式下可能的报错问题.",
			"[美化外观] 优化了 Rematch 皮肤的背景效果. 感谢 gizzmo",
			"[美化外观] 优化了 Legion Remix Helper 收藏页面美化的稳定性.",
			"[美化外观] 优化了 Auctionator 皮肤.",
			"[美化外观] 优化了 RareScanner 皮肤.",
			"[美化外观] 优化了 SilverDragon 皮肤.",
			"[美化外观] 优化了 World Quest Tab 皮肤.",
			"[美化外观] 优化了 BugSack 皮肤.",
			"[美化外观] 优化了编辑框皮肤. (仅限中文客户端)",
			"[美化外观] 优化了 UIErrorsFrame 宽度调整的稳定性.",
			"[小地图按钮] 优化了 Rematch 和 WIM 小地图按钮的材质清理.",
			"[额外物品条] 新增了一些可开启物品.",
			"[游戏条] 尝试修复在某些情况下系统信息无法正确刷新的问题.",
			"[装备观察] 优化了自动布局的稳定性.",
			"[任务列表] 改善了美化的安全性, 防止某些情况下的污染问题.",
			"[战斗提示] 支持进入战斗和离开战斗时的不同渐变色配置.",
			"[商人页面扩展] 优化了扩展页面中的物品按钮美化.",
		},
		["zhTW"] = {
			"[美化外觀] 優化了場景中的法術按鍵.",
			"[美化外觀] 優化了新建天賦配置的介面.",
			"[美化外觀] 修復了 Rematch 皮膚在獨立模式下可能的報錯問題.",
			"[美化外觀] 優化了 Rematch 皮膚的背景效果. 感謝 gizzmo",
			"[美化外觀] 優化了 Legion Remix Helper 收藏頁面美化的穩定性.",
			"[美化外觀] 優化了 Auctionator 皮膚.",
			"[美化外觀] 優化了 RareScanner 皮膚.",
			"[美化外觀] 優化了 SilverDragon 皮膚.",
			"[美化外觀] 優化了 World Quest Tab 皮膚.",
			"[美化外觀] 優化了 BugSack 皮膚.",
			"[美化外觀] 優化了編輯框皮膚. (僅限中文客戶端)",
			"[美化外觀] 優化了 UIErrorsFrame 寬度調整的穩定性.",
			"[小地圖按鍵] 優化了 Rematch 和 WIM 小地圖按鍵的材質清理.",
			"[額外物品條] 新增了一些可開啟物品.",
			"[遊戲條] 嘗試修復在某些情況下系統信息無法正確刷新的問題.",
			"[裝備觀察] 優化了自動佈局的穩定性.",
			"[任務列表] 改善了美化的安全性, 防止某些情況下的污染問題.",
			"[戰鬥提示] 支援進入戰鬥和離開戰鬥時的不同漸變色配置.",
			"[商人頁面擴展] 優化了擴展頁面中的物品按鈕美化.",
		},
		["enUS"] = {
			"[Skins] Optimize spell button frames in scenarios.",
			"[Skins] Add shadow for creating new talent specializations.",
			"[Skins] Fix possible error with Rematch skin in standalone mode.",
			"[Skins] Optimize background effect of Rematch skin. Thanks to gizzmo",
			"[Skins] Improve stability of Legion Remix Helper collection page styling.",
			"[Skins] Optimize Auctionator skin.",
			"[Skins] Optimize RareScanner skin.",
			"[Skins] Optimize SilverDragon skin.",
			"[Skins] Optimize World Quest Tab skin.",
			"[Skins] Optimize BugSack skin.",
			"[Skins] Optimize EditBox skin. (Chinese client only)",
			"[Skins] Optimize UIErrorsFrame skin.",
			"[Minimap Buttons] Optimize texture cleanup for Rematch and WIM minimap buttons.",
			"[Extra Item Bar] Add some activatable items.",
			"[Game Bar] Attempt to fix issue where system info may not refresh correctly in some cases.",
			"[Inspect] Optimize stability of automatic layout.",
			"[Objective Tracker] Improve safety of styling to prevent taints in some cases.",
			"[Combat Alert] Support different gradient color configurations for entering and leaving combat.",
			"[Extend Merchant Pages] Optimize item button skins in extended pages.",
		},
		["koKR"] = {
			"[스킨] 시나리오 내의 주문 버튼 프레임을 최적화했습니다.",
			"[스킨] 새로운 특성 전문화를 생성할 때 그림자를 추가했습니다.",
			"[스킨] 독립 모드에서 Rematch 스킨의 가능한 오류를 수정했습니다.",
			"[스킨] Rematch 스킨의 배경 효과를 최적화했습니다. gizzmo에게 감사합니다",
			"[스킨] Legion Remix Helper 컬렉션 페이지 스킬링의 안정성을 개선했습니다.",
			"[스킨] Auctionator 스킨을 최적화했습니다.",
			"[스킨] RareScanner 스킨을 최적화했습니다.",
			"[스킨] SilverDragon 스킨을 최적화했습니다.",
			"[스킨] World Quest Tab 스킨을 최적화했습니다.",
			"[스킨] BugSack 스킨을 최적화했습니다.",
			"[스킨] 편집 상자 스킨을 최적화했습니다. (중국어 클라이언트 전용)",
			"[스킨] UIErrorsFrame 스킨을 최적화했습니다.",
			"[미니맵 버튼] Rematch 및 WIM 미니맵 버튼의 텍스처 정리를 최적화했습니다.",
			"[추가 아이템 바] 일부 활성화 가능한 아이템을 추가했습니다.",
			"[게임 바] 일부 경우에 시스템 정보가 올바르게 새로 고쳐지지 않는 문제를 수정하려고 시도했습니다.",
			"[장비 살펴보기] 자동 레이아웃의 안정성을 최적화했습니다.",
			"[퀘스트 추적기] 일부 경우에 오염을 방지하기 위해 스타일링의 안전성을 향상시켰습니다.",
			"[전투 알림] 전투 진입 및 퇴장 시 서로 다른 그라데이션 색상 구성을 지원합니다.",
			"[상인 페이지 확장] 확장된 페이지의 아이템 버튼 스킨을 최적화했습니다.",
		},
		["ruRU"] = {
			"[Скины] Оптимизированы кнопки заклинаний в сценариях.",
			"[Скины] Добавлена тень для создания новых специализаций талантов.",
			"[Скины] Исправлена возможная ошибка скина Rematch в автономном режиме.",
			"[Скины] Оптимизирован фоновый эффект скина Rematch. Спасибо gizzmo",
			"[Скины] Улучшена стабильность стилизации страницы коллекций Legion Remix Helper.",
			"[Скины] Оптимизирован скин Auctionator.",
			"[Скины] Оптимизирован скин RareScanner.",
			"[Скины] Оптимизирован скин SilverDragon.",
			"[Скины] Оптимизирован скин World Quest Tab.",
			"[Скины] Оптимизирован скин BugSack.",
			"[Скины] Оптимизирован скин EditBox. (Только для китайского клиента)",
			"[Скины] Оптимизирован скин UIErrorsFrame.",
			"[Кнопки миникарты] Оптимизирована очистка текстур для кнопок миникарты Rematch и WIM.",
			"[Дополнительная панель предметов] Добавлены некоторые активируемые предметы.",
			"[Игровая панель] Попытка исправить проблему, из-за которой системная информация может некорректно обновляться в некоторых случаях.",
			"[Осмотр] Оптимизирована стабильность автоматической компоновки.",
			"[Список заданий] Повышена безопасность стилизации для предотвращения загрязнения в некоторых случаях.",
			"[Оповещение в бою] Поддержка различных конфигураций градиентных цветов при входе и выходе из боя.",
			"[Расширение страниц торговца] Оптимизированы скины кнопок предметов на расширенных страницах.",
		},
	},
}
