local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[403] = {
	RELEASE_DATE = "TBD",
	IMPORTANT = {
		["zhCN"] = {
			"代码清理与优化.",
			"新增军团幻境阶段 2 和 3 史诗钥石地下城数据.",
			"[任务] 分类更名为 [任务成就].",
			"[自动成就截图] 从 [其他] 移至 [任务成就], 新增详细设置选项.",
			"[成就追踪] 从 [其他] 移至 [任务成就].",
			"[已知物品上色] 修复与其他隐藏物品插件(如 Legion Remix Helper)的兼容性问题.",
			"[交接] 重构过滤逻辑, 新增账号完成、可重复任务和其他三个过滤选项.",
			"[事件追踪器] 新增军团突袭事件, 默认禁用其他事件提示音.",
		},
		["zhTW"] = {
			"代碼清理與優化.",
			"新增軍團混搭再造階段 2 和 3 傳奇鑰石地城資料.",
			"[任務] 分類更名為 [任務成就].",
			"[自動成就擷圖] 從 [其他] 移至 [任務成就], 新增詳細設定選項.",
			"[成就追蹤] 從 [其他] 移至 [任務成就].",
			"[已知物品上色] 修復與其他隱藏物品插件(如 Legion Remix Helper)的相容性問題.",
			"[交接] 重構過濾邏輯, 新增帳號完成、可重複任務和其他三個過濾選項.",
			"[事件追蹤器] 新增軍團突襲事件, 預設停用其他事件提示音.",
		},
		["enUS"] = {
			"Code cleanup and optimization.",
			"Added Mythic+ dungeon data for Legion Remix Phase 2 and Phase 3.",
			"[Quest] Category renamed to [Quest & Achieve].",
			"[Auto Screenshot] moved from [Misc] to [Quest & Achieve] with new detailed settings.",
			"[Achievement Tracker] moved from [Misc] to [Quest & Achieve].",
			"[Already Known] Fixed compatibility issues with other item hiding addons (e.g., Legion Remix Helper).",
			"[Turn In] Reworked filtering logic with three new options: Account Completed, Repeatable, and Others.",
			"[Event Tracker] Added Legion Assault support, disabled alert sounds for other events by default.",
		},
		["koKR"] = {
			"코드 정리 및 최적화.",
			"군단 리믹스 2, 3단계 전설 쐐기돌 던전 데이터 추가.",
			"[퀘스트] 카테고리명을 [퀘스트 및 업적]으로 변경.",
			"[자동 스크린샷] [기타]에서 [퀘스트 및 업적]으로 이동, 세부 설정 옵션 추가.",
			"[업적 추적기] [기타]에서 [퀘스트 및 업적]으로 이동.",
			"[이미 알고 있는 아이템] 다른 아이템 숨김 애드온(예: Legion Remix Helper)과의 호환성 문제 수정.",
			"[퀘스트 완료] 필터링 로직 재구성, 계정 완료, 반복 가능, 기타 세 가지 새 옵션 추가.",
			"[이벤트 추적기] 군단 습격 지원 추가, 다른 이벤트 경고음은 기본적으로 비활성화.",
		},
		["ruRU"] = {
			"Очистка и оптимизация кода.",
			"Добавлены данные М+ подземелий для Legion Remix фаз 2 и 3.",
			"[Задания] Категория переименована в [Задания и достижения].",
			"[Автоматический скриншот] перемещен из [Разное] в [Задания и достижения] с новыми детальными настройками.",
			"[Трекер достижений] перемещен из [Разное] в [Задания и достижения].",
			"[Уже известные] Исправлены проблемы совместимости с другими аддонами скрытия предметов (например, Legion Remix Helper).",
			"[Сдача заданий] Переработана логика фильтрации с тремя новыми опциями: Завершено на аккаунте, Повторяемые, Другие.",
			"[Трекер событий] Добавлена поддержка Легионского вторжения, звуковые оповещения для других событий отключены по умолчанию.",
		},
	},
	NEW = {
		["zhCN"] = {
			"[矩形小地图] 新增 HereBeDragons-Pins 图标支持, 默认启用. HandyNotes, SilverDragon 等插件的图标将不再显示在矩形小地图之外.",
			"[事件追踪器] 新增军团幻境军团突袭事件支持.",
		},
		["zhTW"] = {
			"[矩形小地圖] 新增 HereBeDragons-Pins 圖示支援, 預設啟用. HandyNotes, SilverDragon 等插件的圖示將不再顯示在矩形小地圖之外.",
			"[事件追蹤器] 新增軍團混搭再造軍團突襲事件支援.",
		},
		["enUS"] = {
			"[Rectangular Minimap] Added HereBeDragons-Pins support, enabled by default. Icons from addons like HandyNotes, SilverDragon, etc., will no longer appear outside the rectangle minimap.",
			"[Event Tracker] Added Legion Assault event support.",
		},
		["koKR"] = {
			"[사각형 미니맵] HereBeDragons-Pins 지원 추가, 기본 활성화. HandyNotes, SilverDragon 등의 애드온 아이콘이 사각형 미니맵 외부에 더 이상 표시되지 않습니다.",
			"[이벤트 추적기] 군단 습격 이벤트 지원 추가.",
		},
		["ruRU"] = {
			"[Прямоугольная миникарта] Добавлена поддержка HereBeDragons-Pins, включена по умолчанию. Иконки из аддонов, таких как HandyNotes, SilverDragon и др., больше не будут отображаться за пределами прямоугольной миникарты.",
			"[Трекер событий] Добавлена поддержка событий Легионского вторжения.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[美化皮肤] 优化社区窗口皮肤.",
			"[美化皮肤] 优化物品获得提示皮肤.",
			"[美化皮肤] 优化 TomTom 皮肤, 感谢 Merathilis.",
			"[美化皮肤] 重构选框皮肤, 提升地下城选择界面等处的兼容性.",
			"[美化皮肤] 选框皮肤扩展至暴雪设置界面.",
			"[交接] 提升多任务处理稳定性.",
			"[自动截图] 修复战斗提示无法在截图时自动隐藏的问题.",
			"[自动截图] 优化多成就同时获得时的截图逻辑.",
			"[成就追踪] 扩展奖励显示类型.",
			"[成就追踪] 搜索新增奖励过滤, 支持关键词筛选(如'坐骑').",
			"[预创建队伍] 优化简体中文缩写显示.",
			"[预创建队伍] 军团幻境钥石信息移至右侧面板显示.",
			"[进度] 优化大使任务进度通报逻辑, 仅在进度更新时触发.",
			"[进度] 优化任务完成通报逻辑, 避免重复通报.",
			"[进度] 新增史诗钥石地下城任务进度开关, 默认开启.",
			"[鼠标提示]-[钥石] 优化与 Details、BigWigs 的通信逻辑.",
			"[通告]-[实用技能] 新增军团幻境召唤卷轴通告支持.",
			"[通告]-[任务] 修复任务完成通告异常问题.",
			"[通告]-[任务] 新增任务等级与玩家等级相同时自动隐藏选项, 默认开启.",
			"[通告]-[任务] 新增任务等级与满级相同时自动隐藏选项, 默认开启.",
			"[通告]-[任务] 微调任务各阶段通告格式, 新增自定义格式选项.",
			"[已知物品上色] 优化物品识别逻辑, 提升已知/已学物品判定准确性.",
			"[事件追踪器] 调整部分追踪条颜色.",
			"[事件追踪器] 修复简体中文翻译错误.",
			"[物品等级] 修复自动分解插件快速操作导致的错误.",
		},
		["zhTW"] = {
			"[美化皮膚] 優化社群視窗皮膚.",
			"[美化皮膚] 優化物品獲得提示皮膚.",
			"[美化皮膚] 優化 TomTom 皮膚, 感謝 Merathilis.",
			"[美化皮膚] 重構選框皮膚, 提升地城選擇介面等處的相容性.",
			"[美化皮膚] 選框皮膚擴展至暴雪設定介面.",
			"[交接] 提升多任務處理穩定性.",
			"[自動擷圖] 修復戰鬥提示無法在擷圖時自動隱藏的問題.",
			"[自動擷圖] 優化多成就同時獲得時的擷圖邏輯.",
			"[成就追蹤] 擴展獎勵顯示類型.",
			"[成就追蹤] 搜尋新增獎勵過濾, 支援關鍵詞篩選(如「坐騎」).",
			"[預組隊伍] 優化簡體中文縮寫顯示.",
			"[預組隊伍] 軍團混搭再造鑰石資訊移至右側面板顯示.",
			"[進度] 優化大使任務進度通報邏輯, 僅在進度更新時觸發.",
			"[進度] 優化任務完成通報邏輯, 避免重複通報.",
			"[進度] 新增傳奇鑰石地城任務進度開關, 預設開啟.",
			"[浮動提示]-[鑰石] 優化與 Details、BigWigs 的通訊邏輯.",
			"[通告]-[實用技能] 新增軍團混搭再造召喚卷軸通告支援.",
			"[通告]-[任務] 修復任務完成通告異常問題.",
			"[通告]-[任務] 新增任務等級與玩家等級相同時自動隱藏選項, 預設開啟.",
			"[通告]-[任務] 新增任務等級與滿級相同時自動隱藏選項, 預設開啟.",
			"[通告]-[任務] 微調任務各階段通告格式, 新增自訂格式選項.",
			"[已知物品上色] 優化物品識別邏輯, 提升已知/已學物品判定準確性.",
			"[事件追蹤器] 調整部分追蹤條顏色.",
			"[事件追蹤器] 修復簡體中文翻譯錯誤.",
			"[物品等級] 修復自動分解插件快速操作導致的錯誤.",
		},
		["enUS"] = {
			"[Skins] Improved Communities frame skin.",
			"[Skins] Enhanced item received alert skin.",
			"[Skins] Improved TomTom skin. Thanks to Merathilis.",
			"[Skins] Refactored checkbox skinning for better compatibility in dungeon selection and similar interfaces.",
			"[Skins] Extended checkbox skinning to Blizzard Settings.",
			"[Turn In] Enhanced multi-quest handling stability.",
			"[Auto Screenshot] Fixed combat alert not hiding during screenshot capture.",
			"[Auto Screenshot] Optimized logic for simultaneous achievement awards.",
			"[Achievement Tracker] Extended reward display types.",
			"[Achievement Tracker] Added reward filtering with keyword search support (e.g., 'mount').",
			"[LFG List] Optimized Simplified Chinese abbreviations.",
			"[LFG List] Moved keystone info to right panel in Legion Remix.",
			"[Progress] Optimized emissary quest progress alerts, only triggers on updates.",
			"[Progress] Optimized quest completion alerts to prevent duplicates.",
			"[Progress] Added M+ quest progress toggle, enabled by default.",
			"[Tooltip]-[Keystone] Enhanced communication with Details and BigWigs.",
			"[Announcement]-[Utilities] Added Legion Remix summoning scroll announcements.",
			"[Announcement]-[Quest] Fixed quest completion announcement issues.",
			"[Announcement]-[Quest] Added auto-hide level when matching player level, enabled by default.",
			"[Announcement]-[Quest] Added auto-hide level when matching max level, enabled by default.",
			"[Announcement]-[Quest] Refined quest stage announcement formats with customization options.",
			"[Already Known] Enhanced item identification logic for better known/learned detection.",
			"[Event Tracker] Adjusted tracking bar colors.",
			"[Event Tracker] Fixed Simplified Chinese translation errors.",
			"[Item Level] Fixed errors from rapid auto-scrapping addon operations.",
		},
		["koKR"] = {
			"[스킨] 커뮤니티 창 스킨 개선.",
			"[스킨] 아이템 획득 알림 스킨 향상.",
			"[스킨] TomTom 스킨 개선. Merathilis에게 감사.",
			"[스킨] 던전 선택 등 인터페이스에서의 체크박스 스킨 호환성 향상.",
			"[스킨] 체크박스 스킨을 블리자드 설정으로 확장.",
			"[퀘스트 완료] 다중 퀘스트 처리 안정성 향상.",
			"[자동 스크린샷] 스크린샷 시 전투 알림 숨김 오류 수정.",
			"[자동 스크린샷] 동시 달성 논리 최적화.",
			"[업적 추적기] 보상 표시 유형 확장.",
			"[업적 추적기] 키워드 검색 보상 필터링 추가(예: '탈것').",
			"[사전 생성 파티] 간체 중국어 약어 최적화.",
			"[사전 생성 파티] 군단 리믹스에서 쐐기돌 정보를 오른쪽 패널로 이동.",
			"[진행 상황] 대사관 퀘스트 진행 알림 최적화, 업데이트 시만 트리거.",
			"[진행 상황] 퀘스트 완료 알림 최적화로 중복 방지.",
			"[진행 상황] M+ 퀘스트 진행 토글 추가, 기본 활성화.",
			"[툴팁]-[쐐기돌] Details, BigWigs 통신 논리 개선.",
			"[공지]-[유틸리티] 군단 리믹스 소환 두루마리 공지 추가.",
			"[공지]-[퀘스트] 퀘스트 완료 공지 문제 수정.",
			"[공지]-[퀘스트] 플레이어 레벨과 일치 시 레벨 자동 숨김 추가, 기본 활성화.",
			"[공지]-[퀘스트] 최대 레벨과 일치 시 레벨 자동 숨김 추가, 기본 활성화.",
			"[공지]-[퀘스트] 퀘스트 단계 공지 형식 정교화 및 사용자 정의 옵션.",
			"[이미 알고 있는 아이템] 더 나은 알려진/학습된 감지를 위한 아이템 식별 논리 개선.",
			"[이벤트 추적기] 추적 막대 색상 조정.",
			"[이벤트 추적기] 간체 중국어 번역 오류 수정.",
			"[아이템 레벨] 빠른 자동 분해 애드온 작업 오류 수정.",
		},
		["ruRU"] = {
			"[Скины] Улучшен скин фрейма Сообщества.",
			"[Скины] Улучшен скин оповещения о получении предмета.",
			"[Скины] Улучшен скин TomTom. Спасибо Merathilis.",
			"[Скины] Рефакторинг скина флажков для лучшей совместимости в выборе подземелий и подобных интерфейсах.",
			"[Скины] Расширено оформление флажков на настройки Blizzard.",
			"[Сдача заданий] Повышена стабильность обработки нескольких заданий.",
			"[Автоматический скриншот] Исправлено отсутствие скрытия боевого оповещения при создании скриншота.",
			"[Автоматический скриншот] Оптимизирована логика одновременного получения достижений.",
			"[Трекер достижений] Расширены типы отображения наград.",
			"[Трекер достижений] Добавлена фильтрация наград с поддержкой поиска по ключевым словам (например, 'маунт').",
			"[Список LFG] Оптимизированы аббревиатуры для упрощенного китайского.",
			"[Список LFG] Информация о ключах М+ перемещена на правую панель в Legion Remix.",
			"[Прогресс] Оптимизированы оповещения о прогрессе заданий эмиссаров, срабатывают только при обновлениях.",
			"[Прогресс] Оптимизированы оповещения о выполнении заданий для предотвращения дублирования.",
			"[Прогресс] Добавлен переключатель прогресса заданий в М+, включен по умолчанию.",
			"[Подсказка]-[М+ ключ] Улучшено взаимодействие с Details и BigWigs.",
			"[Объявления]-[Утилиты] Добавлены объявления о свитках призыва Legion Remix.",
			"[Объявления]-[Задания] Исправлены проблемы с объявлениями о выполнении заданий.",
			"[Объявления]-[Задания] Добавлено авто-скрытие уровня при совпадении с уровнем игрока, включено по умолчанию.",
			"[Объявления]-[Задания] Добавлено авто-скрытие уровня при совпадении с максимальным уровнем, включено по умолчанию.",
			"[Объявления]-[Задания] Уточнены форматы объявлений этапов заданий с опциями настройки.",
			"[Уже известные] Улучшена логика идентификации предметов для лучшего обнаружения известных/изученных.",
			"[Трекер событий] Настроены цвета полос отслеживания.",
			"[Трекер событий] Исправлены ошибки перевода на упрощенный китайский.",
			"[Уровень предмета] Исправлены ошибки от быстрых операций аддонов автоматической утилизации.",
		},
	},
}
