local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[404] = {
	RELEASE_DATE = "TBD",
	IMPORTANT = {
		["zhCN"] = {
			"最低支持 ElvUI 版本提升至 14.03.",
			"新增了 6 个音效, WT Accept, WT Complete, WT Win, WT Simple, WT Clear, WT Success. 你可以在工具箱或者其他插件如 BigWigs 中使用这些音效.",
		},
		["zhTW"] = {
			"最低支援 ElvUI 版本提升至 14.03.",
			"新增了 6 個音效, WT Accept, WT Complete, WT Win, WT Simple, WT Clear, WT Success. 你可以在工具箱或者其他插件如 BigWigs 中使用這些音效.",
		},
		["enUS"] = {
			"Minimum supported ElvUI version raise to 14.03.",
			"Add 6 new sound effects: WT Accept, WT Complete, WT Win, WT Simple, WT Clear, WT Success. You can use these sound effects in the WindTools or other addons like BigWigs.",
		},
		["koKR"] = {
			"지원되는 최소 ElvUI 버전이 14.03으로 상향됩니다.",
			"6개의 새로운 사운드 효과가 추가됩니다: WT Accept, WT Complete, WT Win, WT Simple, WT Clear, WT Success. 이 사운드 효과는 WindTools 또는 BigWigs와 같은 다른 애드온에서 사용할 수 있습니다.",
		},
		["ruRU"] = {
			"Минимальная поддерживаемая версия ElvUI повышается до 14.03.",
			"Добавляется 6 новых звуковых эффектов: WT Accept, WT Complete, WT Win, WT Simple, WT Clear, WT Success. Вы можете использовать эти звуковые эффекты в WindTools или других аддонах, таких как BigWigs.",
		},
	},
	NEW = {
		["zhCN"] = {},
		["zhTW"] = {},
		["enUS"] = {},
		["koKR"] = {},
		["ruRU"] = {},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[美化皮肤] 重新制作暴雪背包和银行的皮肤, 同时优化 ElvUI 皮肤处理来解决与其他插件如 Zygor 混用时的边框渲染问题.",
			"[美化皮肤] 优化好友界面的美化皮肤.",
			"[移动框体] 优化好友界面子框体的移动.",
			"[战斗提示] 稍微调整离开战斗文字的起始位置.",
			"[额外物品条] 更新可开启物品列表.",
			"[事件追踪器] 优化条的颜色显示逻辑, 现在在等待时均显示为灰色.",
			"[事件追踪器] 优化通知文字的颜色渲染逻辑, 事件名将统一为黄色, 时间部分将会统一为绿色.",
			"[通告]-[任务] 完成世界任务时现在会进行通报.",
			"[进度] 优化世界任务完成进度的触发逻辑, 现在在任务完成后会更及时的展示进度.",
			"[交接] 优化部分任务自动交接逻辑, 特别是军团幻境每日任务的处理.",
			"[矩形小地图] 进一步提升和使用HereBeDragons-Pins库的插件的兼容性, 能够更加严格的隐藏超出矩形小地图边界的图标.",
		},
		["zhTW"] = {
			"[美化皮膚] 重新製作暴雪背包和銀行的皮膚, 同時優化 ElvUI 皮膚處理來解決與其他插件如 Zygor 混用時的邊框渲染問題.",
			"[美化皮膚] 優化好友介面的美化皮膚.",
			"[移動框架] 優化好友介面子框架的移動.",
			"[戰鬥提示] 稍微調整離開戰鬥文字的起始位置.",
			"[額外物品條] 更新可開啟物品清單.",
			"[事件追蹤器] 優化條的顏色顯示邏輯, 現在在等待時均顯示為灰色.",
			"[事件追蹤器] 優化通知文字的顏色渲染邏輯, 事件名將統一為黃色, 時間部分將會統一為綠色.",
			"[通告]-[任務] 完成世界任務時現在會進行通報.",
			"[進度] 優化世界任務完成進度的觸發邏輯, 現在在任務完成後會更及時的展示進度.",
			"[交接] 優化部分任務自動交接邏輯, 特別是軍團幻境每日任務的處理.",
			"[矩形小地圖] 進一步提升和使用HereBeDragons-Pins庫的插件的相容性, 能夠更加嚴格的隱藏超出矩形小地圖邊界的圖示.",
		},
		["enUS"] = {
			"[Skins] Redesign Blizzard bag and bank skins, and optimize ElvUI skin handling to resolve border rendering issues when mixing with other addons like Zygor.",
			"[Skins] Optimize friend list skin.",
			"[Move Frames] Optimize movement of friend list subframes.",
			"[Combat Alert] Slightly adjust the starting position of combat text.",
			"[Extra Item Bar] Update the list of items that can be enabled.",
			"[Event Tracker] Optimize bar color display logic, now all bars show as gray when waiting.",
			"[Event Tracker] Optimize notification text color rendering logic, event names will be uniformly yellow, time parts will be uniformly green.",
			"[Announcements]-[Quests] Now announce when world quests are completed.",
			"[Progress] Optimize world quest completion progress trigger logic, now display progress more promptly after quest completion.",
			"[Turn In] Optimize auto turn-in logic for certain quests, especially for the handling of Legion Remix daily quests.",
			"[Rectangle Minimap] Further improve compatibility with addons using the HereBeDragons-Pins library, allowing for stricter hiding of icons that exceed the boundaries of the rectangle minimap.",
		},
		["koKR"] = {
			"[스킨] 블리자드 가방과 은행 스킨을 재디자인하고, ElvUI 스킨 처리를 최적화하여 Zygor와 같은 다른 애드온과 혼합 사용 시 테두리 렌더링 문제를 해결합니다.",
			"[스킨] 친구 목록 스킨을 최적화합니다.",
			"[프레임 이동] 친구 목록 하위 프레임의 이동을 최적화합니다.",
			"[전투 알림] 전투 텍스트의 시작 위치를 약간 조정합니다.",
			"[추가 아이템 바] 활성화할 수 있는 아이템 목록을 업데이트합니다.",
			"[이벤트 추적기] 바 색상 표시 로직을 최적화하여, 이제 대기 중일 때 모든 바가 회색으로 표시됩니다.",
			"[이벤트 추적기] 알림 텍스트 색상 렌더링 로직을 최적화하여, 이벤트 이름은 균일하게 노란색, 시간 부분은 균일하게 녹색으로 표시됩니다.",
			"[공지사항]-[퀘스트] 이제 월드 퀘스트 완료 시 알립니다.",
			"[진행 상황] 월드 퀘스트 완료 진행률 트리거 로직을 최적화하여, 이제 퀘스트 완료 후 진행률을 더 빠르게 표시합니다.",
			"[퀘스트 교환] 특정 퀘스트, 특히 군단 리믹스 일일 퀘스트 처리에 대한 자동 교환 로직이 최적화되었습니다.",
			"[직사각형 미니맵] HereBeDragons-Pins 라이브러리를 사용하는 애드온과의 호환성이 더욱 향상되어, 직사각형 미니맵 경계를 초과하는 아이콘을 더 엄격하게 숨길 수 있습니다.",
		},
		["ruRU"] = {
			"[Скины] Переработаны скины сумок и банка Blizzard, а также оптимизирована обработка скинов ElvUI для решения проблем с рендерингом границ при использовании с другими аддонами, такими как Zygor.",
			"[Скины] Оптимизирован скин списка друзей.",
			"[Перемещение фреймов] Оптимизировано перемещение подфреймов списка друзей.",
			"[Боевое оповещение] Скорректирована начальная позиция текста боя.",
			"[Дополнительная панель предметов] Обновлен список предметов, которые можно включить.",
			"[Отслеживатель событий] Оптимизирована логика отображения цвета полос, теперь все полосы отображаются серым при ожидании.",
			"[Отслеживатель событий] Оптимизирована логика рендеринга цвета текста уведомлений, названия событий будут единообразно желтыми, а части времени - зелеными.",
			"[Объявления]-[Задания] Теперь объявляется о завершении мировых заданий.",
			"[Прогресс] Оптимизирована логика триггера прогресса завершения мировых заданий, теперь прогресс отображается более оперативно после завершения задания.",
			"[Сдача заданий] Оптимизирована логика автоматической сдачи для определенных заданий, особенно для обработки ежедневных заданий Легиона Ремикс.",
			"[Прямоугольная миникарта] Дополнительно улучшена совместимость с аддонами, использующими библиотеку HereBeDragons-Pins, что позволяет более строго скрывать значки, выходящие за пределы прямоугольной миникарты.",
		},
	},
}
