local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[411] = {
	RELEASE_DATE = "2026/02/12",
	IMPORTANT = {
		["zhCN"] = {
			"兼容了 12.0.1 版本 API.",
			"最低支持的 ElvUI 版本提升到 15.05.",
			"SetPassThroughButtons 修复默认停用, 你可以随时在 [高级] 中启用它.",
			"至暗之夜 API 修复已经移除, 改用 ElvUI API 来实现最小化修复.",
			"[通告] 重写了实用技能的通告功能, 现在可以在暴雪不限制的情况下使用通报自己使用的技能.",
			"[小地图点击者] 由于暴雪对于小地图点击事件进行了完全加密, 导致无法再继续支持该功能, 因此该模块被移除.",
		},
		["zhTW"] = {
			"兼容了 12.0.1 版本 API.",
			"最低支持的 ElvUI 版本提升到 15.05.",
			"SetPassThroughButtons 修復默認停用, 你可以隨時在 [進階] 中啟用它.",
			"至暗之夜 API 修復已經移除, 改用 ElvUI API 來實現最小化修復.",
			"[通告] 重寫了實用技能的通告功能, 現在可以在暴雪不限制的情況下使用通報自己使用的技能.",
			"[小地圖點擊者] 由於暴雪對於小地圖點擊事件進行了完全加密, 導致無法再繼續支持該功能, 因此該模塊被移除.",
		},
		["enUS"] = {
			"Compatible with 12.0.1 API.",
			"Minimum supported ElvUI version raised to 15.05.",
			"SetPassThroughButtons fix is disabled by default, you can enable it anytime in [Advanced] settings.",
			"The Darkest Night API fix has been removed, switching to ElvUI API for minimal fix.",
			"[Announcement] Rewrote the announcement feature for utility skills, now you can announce your own skills without Blizzard restrictions.",
			"[Who Clicked Minimap] Due to Blizzard's complete encryption of minimap click events, this feature can no longer be implemented, so the module has been removed.",
		},
		["koKR"] = {
			"12.0.1 API와 호환됩니다.",
			"지원되는 최소 ElvUI 버전이 15.05로 상향되었습니다.",
			"SetPassThroughButtons 수정이 기본적으로 비활성화되어 있으며, [고급] 설정에서 언제든지 활성화할 수 있습니다.",
			"The Darkest Night API 수정이 제거되었으며, 최소한의 수정을 위해 ElvUI API로 전환되었습니다.",
			"[공지] 유틸리티 스킬의 공지 기능을 재작성했습니다. 이제 블리자드의 제한 없이 자신의 스킬을 공지할 수 있습니다.",
			"[미니맵을 클릭한 사람] 블리자드가 미니맵 클릭 이벤트를 완전히 암호화했기 때문에 이 기능을 더 이상 구현할 수 없으므로 모듈이 제거되었습니다.",
		},
		["ruRU"] = {
			"Совместимость с API 12.0.1.",
			"Минимальная поддерживаемая версия ElvUI повышена до 15.05.",
			"Исправление SetPassThroughButtons отключено по умолчанию, Вы можете включить его в любое время в настройках [Дополнительно].",
			"Исправление API 'Непроглядная ночь' было удалено, для минимального исправления используется API ElvUI.",
			"[Оповещения] Переписана функция оповещений для вспомогательных навыков, теперь Вы можете оповещать о своих собственных навыках без ограничений Blizzard.",
			"[Кто нажал на миникарту] Из-за полной шифровки событий кликов по миникарте Blizzard эта функция больше не может быть реализована, поэтому модуль был удален.",
		},
	},
	NEW = {
		["zhCN"] = {
			"[战斗提醒] 新增了进入战斗, 离开战斗的声音设置选项. 默认关闭.",
			"[美化外观] 新增了 ElvUI 姓名板的阴影美化皮肤.",
			"[任务追踪] 新增了任务追踪按钮的位置和缩放调整选项. 默认关闭.",
			"[移动框体] 新增了自动重置离屏框体位置的选项. 默认开启.",
		},
		["zhTW"] = {
			"[戰鬥提醒] 新增了進入戰鬥, 離開戰鬥的聲音設置選項. 默認關閉.",
			"[美化外觀] 新增了 ElvUI 姓名板的陰影美化皮膚.",
			"[任務追蹤] 新增了任務追蹤按鈕的位置和縮放調整選項. 默認關閉.",
			"[移動框架] 新增了自動重置離屏框架位置的選項. 默認開啟.",
		},
		["enUS"] = {
			"[Combat Reminder] Added sound settings options for entering and leaving combat. Disabled by default.",
			"[Skins] Added shadow skin for ElvUI Nameplates.",
			"[Objective Tracker] Added position and scale adjustment options for the POI button. Disabled by default.",
			"[Move Frames] Added an option to automatically reset off-screen frame positions. Enabled by default.",
		},
		["koKR"] = {
			"[전투 알림] 전투 진입 및 퇴장에 대한 사운드 설정 옵션이 추가되었습니다. 기본적으로 비활성화되어 있습니다.",
			"[스킨] ElvUI 이름표에 대한 그림자 스킨이 추가되었습니다.",
			"[퀘스트 추적기] POI 버튼에 대한 위치 및 크기 조정 옵션이 추가되었습니다. 기본적으로 비활성화되어 있습니다.",
			"[프레임 이동] 화면 밖 프레임 위치를 자동으로 재설정하는 옵션이 추가되었습니다. 기본적으로 활성화되어 있습니다.",
		},
		["ruRU"] = {
			"[Боевое напоминание] Добавлены параметры настройки звука для входа и выхода из боя. По умолчанию отключено.",
			"[Скины] Добавлен скин теней для индикаторов здоровья ElvUI.",
			"[Трекер заданий] Добавлены параметры настройки позиции и масштаба для кнопки POI. По умолчанию отключено.",
			"[Перемещение фреймов] Добавлена ​​опция автоматического сброса позиций фреймов за пределами экрана. По умолчанию включено.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"优化了一个全局变量泄露问题.",
			"[通告] 移除了通告模块中所有在战斗中受限的功能.",
			"[护盾] 现在护盾只会在伤害护盾上使用自定义材质.",
			"[额外物品条] 任务物品现在会根据任务距离排序.",
			"[美化外观] 优化了冷却管理器皮肤, 消除了冷却动画和图标之间的空隙.",
			"[移动框体] 优化了对框体位置保存的稳定度, 希望能够减少框体飞出屏幕的情况发生.",
			"[移动框体] 最大程度减少了对框体的数据写入, 以防止出现污染.",
		},
		["zhTW"] = {
			"優化了一個全局變量洩露問題.",
			"[通告] 移除了通告模塊中所有在戰鬥中受限的功能.",
			"[護盾] 現在護盾只會在傷害護盾上使用自定義材質.",
			"[額外物品條] 任務物品現在會根據任務距離排序.",
			"[美化外觀] 優化了冷卻管理器皮膚, 消除了冷卻動畫和圖標之間的空隙.",
			"[移動框架] 優化了對框架位置保存的穩定度, 希望能夠減少框架飛出屏幕的情況發生.",
			"[移動框架] 最大程度減少了對框架的數據寫入, 以防止出現污染.",
		},
		["enUS"] = {
			"Optimized a global variable leak issue.",
			"[Announcement] Removed all in-combat restricted features in Announcement module.",
			"[Absorb] Now custom textures are only applied to damage absorbs.",
			"[Extra Items Bar] Quest items are now sorted by quest distance.",
			"[Skins] Optimized Cooldown Manager skin, eliminating gaps between cooldown animations and icons.",
			"[Move Frames] Optimized the stability of frame position saving, hoping to reduce the occurrence of frames flying off the screen.",
			"[Move Frames] Minimized data writing to frames to prevent taint.",
		},
		["koKR"] = {
			"글로벌 변수 누수 문제를 최적화했습니다.",
			"[공지] 공지 모듈에서 전투 중 제한된 모든 기능을 제거했습니다.",
			"[흡수] 이제 사용자 지정 텍스처가 피해 흡수에만 적용됩니다.",
			"[추가 아이템 바] 퀘스트 아이템이 이제 퀘스트 거리별로 정렬됩니다.",
			"[스킨] 쿨다운 관리자 스킨을 최적화하여 쿨다운 애니메이션과 아이콘 사이의 간격을 제거했습니다.",
			"[프레임 이동] 프레임 위치 저장의 안정성을 최적화하여 프레임이 화면 밖으로 날아가는 현상을 줄이기를 바랍니다.",
			"[프레임 이동] 오염을 방지하기 위해 프레임에 대한 데이터 쓰기를 최소화했습니다.",
		},
		["ruRU"] = {
			"Оптимизирована проблема утечки глобальных переменных.",
			"[Оповещения] Удалены все функции, ограниченные в бою, в модуле 'Оповещения'.",
			"[Поглощение] Теперь пользовательские текстуры применяются только к поглощениям урона.",
			"[Дополнительная панель предметов] Предметы, получаемые в ходе выполнения задания, теперь сортируются по расстоянию до места выполнения задания.",
			"[Скины] Оптимизирован скин для 'Менеджера перезарядок', устранены зазоры между анимациями перезарядки и иконками.",
			"[Перемещение фреймов] Оптимизирована стабильность сохранения позиции фреймов, что должно уменьшить случаи их вылета за пределы экрана.",
			"[Перемещение фреймов] Минимизирована запись данных во фреймы для предотвращения загрязнения.",
		},
	},
}
