local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[412] = {
	RELEASE_DATE = "2026/02/25",
	IMPORTANT = {
		["zhCN"] = {
			"[美化外观] 错误框体皮肤改为使用私有框体并同步原框体显隐逻辑, 以降低污染风险.",
			"[美化外观] 错误框体功能默认开启, 并新增高度选项.",
		},
		["zhTW"] = {
			"[美化外觀] 錯誤框架皮膚改為使用私有框架並同步原框架顯隱邏輯, 以降低污染風險.",
			"[美化外觀] 錯誤框架功能預設開啟, 並新增高度選項.",
		},
		["enUS"] = {
			"[Skins] UI Errors Skin now uses a private frame and synchronizes native frame visibility logic to reduce taint risk.",
			"[Skins] UI Errors Skin is now enabled by default, and a height option has been added.",
		},
		["koKR"] = {
			"[스킨] UI Errors 스킨이 전용 프레임을 사용하고 기본 프레임의 표시/숨김 로직을 동기화하도록 변경되어 오염 위험이 줄어들었습니다.",
			"[스킨] UI Errors 스킨이 기본적으로 활성화되며, 높이 옵션이 추가되었습니다.",
		},
		["ruRU"] = {
			"[Скины] Теперь интерфейс ошибок использует закрытый фрейм и синхронизирует собственную логику видимости фрейма для снижения риска загрязнения.",
			"[Скины] Теперь интерфейс ошибок включен по умолчанию, также добавлена ​​опция регулировки высоты.",
		},
	},
	NEW = {
		["zhCN"] = {
			"[数据条] 在微型菜单中新增了任务和家宅选项.",
			"[小地图按钮] 新增了隐藏和忽略正则表达式的选项. 部分代码来自 E11, 感谢贡献",
			"[美化外观] 新增了 HandyNotes MapNotes 的皮肤.",
			"[美化外观] 新增了独立的伤害统计界面皮肤, 可以在 [美化外观] - [伤害统计] 中找到.",
			"[游戏条] 现在炉石按钮支持回退选项, 当选定的炉石不可用时可以自动切换到备用选项.",
			"[游戏条] 炉石按钮现在可以选择法术了, 比如萨满的星界转移.",
			"[游戏条] 新增炉石按钮鼠标中键设定项, 可以设置为使用不同的物品或法术.",
		},
		["zhTW"] = {
			"[數據條] 在微型菜單中新增了任務和住宅選項.",
			"[小地圖按鈕] 新增了隱藏和忽略正則表達式的選項. 部分代碼來自 E11, 感謝貢獻",
			"[美化外觀] 新增了 HandyNotes MapNotes 的皮膚.",
			"[美化外觀] 新增了獨立的傷害統計界面皮膚, 可以在 [美化外觀] - [傷害統計] 中找到.",
			"[遊戲條] 現在爐石按鈕支持回退選項, 當選定的爐石不可用時可以自動切換到備用選項.",
			"[遊戲條] 爐石按鈕現在可以選擇法術了, 比如薩滿的星界轉移.",
			"[遊戲條] 新增爐石按鈕滑鼠中鍵設定項, 可以設定為使用不同的物品或法術.",
		},
		["enUS"] = {
			"[Datatext] Added Quest and Garrison options to the micro menu.",
			"[Minimap Button] Added options for hiding and ignoring regex. Part of the code is from E11, thanks for the contribution.",
			"[Skins] Added skin for HandyNotes MapNotes.",
			"[Skins] Added a separate skin for damage statistics interface, which can be found in [Skins] - [Damage Meter].",
			"[Game Bar] Now the hearthstone button support fallback options, which can automatically switch to the fallback item when the selected hearthstone is not available.",
			"[Game Bar] Hearthstone button can now select spells, such as Shaman's Astral Recall.",
			"[Game Bar] Added middle mouse button setting for hearthstone button, which can be set to use different items or spells.",
		},
		["koKR"] = {
			"[데이터바] 마이크로 메뉴에 퀘스트와 주둔지 옵션이 추가되었습니다.",
			"[미니맵 버튼] 숨기기 및 무시 정규식 옵션이 추가되었습니다. 일부 코드는 E11에서 가져온 것으로, 기여에 감사드립니다.",
			"[스킨] HandyNotes MapNotes의 스킨이 추가되었습니다.",
			"[스킨] 피해 통계 인터페이스에 별도의 스킨이 추가되었으며, [스킨] - [데미지 미터]에서 찾을 수 있습니다.",
			"[게임 바] 이제 하스스톤 버튼이 대체 옵션을 지원하여 선택한 하스스톤을 사용할 수 없는 경우 대체 아이템으로 자동 전환할 수 있습니다.",
			"[게임 바] 하스스톤 버튼이 이제 주문을 선택할 수 있습니다, 예를 들어 샤먼의 천체 소환.",
			"[게임 바] 하스스톤 버튼에 마우스 중간 버튼 설정이 추가되어 다른 아이템이나 주문을 사용할 수 있도록 설정할 수 있습니다.",
		},
		["ruRU"] = {
			"[Текст данных] В микроменю добавлены опции 'Задания' и 'Гарнизон'.",
			"[Кнопка миникарты] Добавлены опции для скрытия и игнорирования регулярных выражений. Часть кода взята из E11, спасибо за вклад.",
			"[Скины] Добавлена тема для HandyNotes MapNotes.",
			"[Скины] Добавлена отдельная тема для интерфейса статистики урона, которую можно найти в [Скины] - [Дамагметр].",
			"[Игровая панель] Теперь кнопка камня возвращения поддерживает опции резервного использования, которые могут автоматически переключаться на запасной предмет, когда выбранный камень возвращения недоступен.",
			"[Игровая панель] Кнопка камня возвращения теперь может выбирать заклинания, такие как Астральная телепортация шамана.",
			"[Игровая панель] Добавлена настройка средней кнопки мыши для кнопки камня возвращения, которая может быть настроена на использование различных предметов или заклинаний.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[美化外观] 修复了 Simple Addon Manager 皮肤.",
			"[美化外观] 优化了 Collectionator 皮肤, 支持其最新的家具页面.",
			"[美化外观] 为 ElvUI 姓名板皮肤添加了光环图标的阴影边框.",
			"[美化外观] 优化了公会社区界面皮肤, 降低了导致污染的可能性.",
			"[美化外观] 优化了冷却管理器管理界面皮肤, 降低了导致污染的可能性.",
			"[鼠标提示] 修复了多个在鼠标提示信息查询时可能出现的错误.",
			"[世界地图] 修复了去除迷雾在破碎群岛地图上可能无法正确显示阿古斯区域的问题.",
			"[智能 Tab] 修复了战斗中尝试记录密语目标时可能出现的秘密值错误.",
			"[聊天文字] 同步 ElvUI 聊天代码, 提升稳定性.",
			"[聊天文字] 修复服务器带有空格时无法通过点击快速设定密语目标的问题.",
			"[快速焦点] 优化了使用非左键时可能无法正确设置焦点的问题.",
		},
		["zhTW"] = {
			"[美化外觀] 修復了 Simple Addon Manager 皮膚.",
			"[美化外觀] 優化了 Collectionator 皮膚, 支持其最新的家具頁面.",
			"[美化外觀] 為 ElvUI 姓名板皮膚添加了光環圖標的陰影邊框.",
			"[美化外觀] 優化了公會社區界面皮膚, 降低了導致污染的可能性.",
			"[美化外觀] 優化了冷卻管理器管理界面皮膚, 降低了導致污染的可能性.",
			"[浮動提示] 修復了多個在滑鼠提示資訊查詢時可能出現的錯誤.",
			"[世界地圖] 修復了去除迷霧在破碎群島地圖上可能無法正確顯示阿古斯區域的問題.",
			"[智能 Tab] 修復了戰鬥中嘗試記錄密語目標時可能出現的秘密值錯誤.",
			"[聊天文字] 同步 ElvUI 聊天代碼, 提升穩定性.",
			"[聊天文字] 修復伺服器帶有空格時無法通過點擊快速設定密語目標的問題.",
			"[快速焦點] 優化了使用非左鍵時可能無法正確設置焦點的問題.",
		},
		["enUS"] = {
			"[Skins] Fixed the skin for Simple Addon Manager.",
			"[Skins] Optimized the skin for Collectionator, supporting its decor page.",
			"[Skins] Added shadow borders to the aura icons for ElvUI Nameplate skin.",
			"[Skins] Optimized the skin for Guild & Community, reducing the possibility of causing taint.",
			"[Skins] Optimized the skin for Cooldown Manager Setting, reducing the possibility of causing taint.",
			"[Tooltips] Fixed multiple errors that may occur when querying tooltip information.",
			"[World Map] Fixed an issue where removing fog of war may not correctly display the Argus area on the Broken Isles map.",
			"[Smart Tab] Fixed a secret value error that may occur when trying to record whisper targets during combat.",
			"[Chat Text] Synchronized ElvUI chat code for improved stability.",
			"[Chat Text] Fixed an issue where clicking to quickly set whisper targets may not work when the server has spaces.",
			"[Quick Focus] Optimized an issue where using non-left-click may not set focus correctly.",
		},
		["koKR"] = {
			"[스킨] Simple Addon Manager 스킨이 수정되었습니다.",
			"[스킨] Collectionator 스킨이 최적화되어 최신 가구 페이지를 지원합니다.",
			"[스킨] ElvUI 이름표 스킨에 오라 아이콘의 그림자 테두리가 추가되었습니다.",
			"[스킨] 길드 및 커뮤니티 스킨이 최적화되어 오염 가능성이 줄어들었습니다.",
			"[스킨] 쿨다운 관리자 설정 스킨이 최적화되어 오염 가능성이 줄어들었습니다.",
			"[툴팁] 툴팁 정보를 조회할 때 발생할 수 있는 여러 오류가 수정되었습니다.",
			"[세계 지도] 안개 제거가 부서진 섬 지도에서 아르거스 지역을 올바르게 표시하지 못할 수 있는 문제를 수정했습니다.",
			"[스마트 탭] 전투 중 귓속말 대상 기록 시 발생할 수 있는 비밀 값 오류를 수정했습니다.",
			"[채팅 텍스트] ElvUI 채팅 코드를 동기화하여 안정성을 향상시켰습니다.",
			"[채팅 텍스트] 서버에 공백이 있을 때 클릭하여 귓속말 대상을 빠르게 설정할 수 없는 문제를 수정했습니다.",
			"[빠른 집중] 비왼쪽 클릭을 사용할 때 집중 설정이 올바르게 되지 않을 수 있는 문제를 최적화했습니다.",
		},
		["ruRU"] = {
			"[Скины] Исправлена тема для Simple Addon Manager.",
			"[Скины] Оптимизирована тема для Collectionator, поддерживающая его последнюю страницу декора.",
			"[Скины] Добавлены теневые границы к иконкам аур для темы табличек с именем ElvUI.",
			"[Скины] Оптимизирована тема для Гильдии и Сообщества, что снижает вероятность загрязнения.",
			"[Скины] Оптимизирована тема для настроек Менеджера перезарядки, что снижает вероятность загрязнения.",
			"[Подсказки] Исправлено несколько ошибок, которые могут возникать при запросе информации в подсказках.",
			"[Карта мира] Исправлена проблема, из-за которой удаление тумана войны может некорректно отображать область Аргуса на карте Расколотых островов.",
			"[Умная вкладка] Исправлена ошибка секретного значения, которая может возникать при попытке записать цели шепота во время боя.",
			"[Текст чата] Синхронизирован код чата ElvUI для улучшения стабильности.",
			"[Текст чата] Исправлена проблема, из-за которой при клике для быстрого назначения целей шепота может не работать, если сервер содержит пробелы.",
			"[Быстрый фокус] Оптимизирована проблема, из-за которой использование не левой кнопки мыши может неправильно устанавливать фокус.",
		},
	},
}
