local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[414] = {
	RELEASE_DATE = "2026/03/07",
	IMPORTANT = {
		["zhCN"] = {
			"最低支持的 ElvUI 版本提升到 15.08.",
			"更新了 LibRangeCheck-3.0 库, 能够更加准确地检测距离.",
			"调整了任务交接相关的选项名称和描述. 由于默认设定是不会自动交接账户未完成且非日常任务的, 你需要手动去设定中启用条件才能在全部任务上生效.",
			"优化了简体中文客户端中反和谐功能, 现在不会污染到好友列表导致无法使用访问住宅功能了.",
			"[额外物品条] 商人售卖的食品分组 FOODVENDOR 现在不再包含地心之战版本中的食物.",
		},
		["zhTW"] = {
			"ElvUI 最低支援版本提升到 15.08.",
			"更新了 LibRangeCheck-3.0 函式庫, 能夠更加準確地檢測距離.",
			"調整了任務交接相關的選項名稱和描述. 由於預設設置是不會自動交接帳號未完成且非日常任務的, 你需要手動在設置中啟用條件才能在全部任務上生效.",
			"優化了簡體中文客戶端中反和諧功能, 現在不會污染到好友列表導致無法使用訪問住宅功能了.",
			"[額外物品條] 商人售賣的食品分組 FOODVENDOR 現在不再包含地心之戰版本中的食物.",
		},
		["enUS"] = {
			"The minimum supported ElvUI version has been raised to 15.08.",
			"Updated the LibRangeCheck-3.0 library, which can now detect distances more accurately.",
			"Adjusted the names and descriptions of the quest turn-in related options. Since the default setting is not to automatically turn in quests that are account incomplete and non-daily, you will need to manually enable the conditions in the settings for it to take effect on all quests.",
			"Improved the anti-censorship feature in the Simplified Chinese client, which should no longer pollute the friends list and cause the housing access feature to be unusable.",
			"[Extra Item Bar] The group of food sold by vendors 'FOODVENDOR' no longer includes the TWW foods.",
		},
		["koKR"] = {
			"지원하는 ElvUI 버전이 15.08로 상향되었습니다.",
			"LibRangeCheck-3.0 라이브러리가 업데이트되어 거리를 보다 정확하게 감지할 수 있습니다.",
			"퀘스트 인계 관련 옵션의 이름과 설명이 조정되었습니다. 기본 설정은 계정 미완료 및 비일일 퀘스트를 자동으로 인계하지 않도록 되어 있으므로, 모든 퀘스트에 적용하려면 설정에서 조건을 수동으로 활성화해야 합니다.",
			"간체 중국어 클라이언트에서 검열 방지 기능이 개선되어 친구 목록이 오염되어 주택 접근 기능을 사용할 수 없게 되는 문제가 더 이상 발생하지 않습니다.",
			"[추가 아이템 바] 상인이 판매하는 음식 그룹 'FOODVENDOR'에는 더 이상 TWW 음식이 포함되지 않습니다.",
		},
		["ruRU"] = {
			"Минимальная поддерживаемая версия ElvUI повышена до 15.08.",
			"Обновлена библиотека LibRangeCheck-3.0, которая теперь может более точно определять расстояния.",
			"Изменены названия и описания параметров, связанных со сдачей заданий. Поскольку по умолчанию задания, не выполненные на учетной записи и не являющиеся ежедневными, не сдаются автоматически, Вам потребуется вручную включить соответствующие условия в настройках, чтобы они вступили в силу для всех заданий.",
			"Улучшена функция анти-цензуры в клиенте на упрощенном китайском языке, которая больше не должна загрязнять список друзей и делать функцию доступа к жилью недоступной.",
			"[Дополнительная панель предметов] Группа еды, продаваемой торговцами 'FOODVENDOR', больше не включает еду из TWW.",
		},
	},
	NEW = {
		["zhCN"] = {
			"新增了 [战斗] - [取消图腾] 模块, 支持绑定按键或者通过宏命令来取消图腾.",
			"[美化外观] 新增了 Angleur 皮肤.",
			"[事件追踪器] 新增了一些至暗之夜周常和事件的追踪.",
			"[任务追踪] 新增了显示任务标题和追踪器标题为大写的选项. 这只会在非亚洲语言环境下生效. 感谢 Toxi",
			"[游戏条] 新增了炉石按钮鼠标提示中显示炉石绑定位置的选项. 默认开启.",
			"[额外物品条] 添加至暗之夜钓鱼相关物品分组 FISHINGMN. 感谢 LvWind",
		},
		["zhTW"] = {
			"新增了 [戰鬥] - [取消圖騰] 模組, 支持綁定按鍵或者通過宏命令來取消圖騰.",
			"[美化外觀] 新增了 Angleur 皮膚.",
			"[事件追蹤器] 新增了一些至暗之夜周常任務和事件的追蹤.",
			"[任務追蹤] 新增了顯示任務標題和追蹤器標題為大寫的選項. 這只會在非亞洲語言環境下生效. 感謝 Toxi",
			"[遊戲條] 新增了爐石按鍵滑鼠提示中顯示爐石綁定位置的選項. 預設開啟.",
			"[額外物品條] 添加至暗之夜釣魚相關物品分組 FISHINGMN. 感謝 LvWind",
		},
		["enUS"] = {
			"Added a new module [Combat] - [Destroy Totem], which supports binding keys or using macro commands to cancel totems.",
			"[Skins] Added the Angleur skin.",
			"[Event Tracker] Added tracking for some Midnight weekly quests and events.",
			"[Objective Tracker] Added the option to display quest titles and tracker headers in uppercase. This will only take effect in non-Asian locales. Thanks Toxi",
			"[Game Bar] Added the option to display the hearthstone binding location in the tooltip. Enabled by default.",
			"[Extra Item Bar] Added a new group for fishing-related items in Midnight. Thanks LvWind.",
		},
		["koKR"] = {
			"새로운 모듈 [전투] - [토템 파괴]가 추가되어 키 바인딩이나 매크로 명령을 사용하여 토템을 취소할 수 있습니다.",
			"[스킨] Angleur 스킨이 추가되었습니다.",
			"[이벤트 추적기] 일부 자정 주간 퀘스트 및 이벤트에 대한 추적이 추가되었습니다.",
			"[목적 추적기] 퀘스트 제목과 추적기 헤더를 대문자로 표시하는 옵션이 추가되었습니다. 이는 아시아어 로케일이 아닌 경우에만 적용됩니다. Toxi에게 감사드립니다.",
			"[게임 바] 툴팁에 하스스톤 바인딩 위치를 표시하는 옵션이 추가되었습니다. 기본적으로 활성화되어 있습니다.",
			"[추가 아이템 바] 자정의 낚시 관련 아이템을 위한 새로운 그룹이 추가되었습니다. 감사합니다 LvWind.",
		},
		["ruRU"] = {
			"Добавлен новый модуль [Бой] - [Уничтожить тотем], который поддерживает привязку клавиш или использование макрокоманд для отмены тотемов.",
			"[Скины] Добавлен скин Angleur.",
			"[Отслеживатель событий] Добавлено отслеживание некоторых еженедельных заданий и событий Полуночи.",
			"[Отслеживатель задач] Добавлена опция отображения названий заданий и заголовков трекера в верхнем регистре. Это будет работать только в неазиатских локалях. Спасибо Toxi",
			"[Игровая панель] Добавлена опция отображения места привязки камня возвращения в подсказке. Включено по умолчанию.",
			"[Дополнительная панель предметов] Добавлена новая группа для предметов, связанных с рыбалкой в Полуночи. Спасибо LvWind.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[美化外观] 修复了与 World Quest Tab 新版本的兼容性.",
			"[美化外观] 优化了 World Quest Tab 的防错鼠标提示美化, 屏蔽了其中的说明文本显示, 将针对暴雪默认的鼠标提示美化适配到防错鼠标提示上.",
			"[小地图按钮] 优化了与 RestedXP Guides 插件的兼容性, 现在不会再出现一个空白区域了.",
			"[护盾] 优化了护盾材质的显示.",
			"[游戏条] 调整鼠标中键点击的默认设置为传送到奥术秘社.",
			"[游戏条] 现在随机炉石的图标会显示随机到的下一个炉石的图标, 而不是固定显示问号图标了.",
			"[额外物品条] 添加更多可开启物品.",
			"[额外物品条] 更新了实用物品分组的部分工程学物品列表. 感谢 LvWind",
			"[额外物品条] 修复了至暗之夜版本物品品质图标不正确的问题.",
		},
		["zhTW"] = {
			"[美化外觀] 修復了與 World Quest Tab 新版本的相容性.",
			"[美化外觀] 優化了 World Quest Tab 的防錯滑鼠提示美化, 屏蔽了其中的說明文本顯示, 將針對暴雪預設的滑鼠提示美化適配到防錯滑鼠提示上.",
			"[小地圖按鍵] 優化了與 RestedXP Guides 插件的相容性, 現在不會再出現一個空白區域了.",
			"[護盾] 優化了護盾材質的顯示.",
			"[遊戲條] 調整滑鼠中鍵點擊的預設設定為傳送到亞肯提納.",
			"[遊戲條] 現在隨機爐石的圖示會顯示隨機到的下一個爐石的圖示, 而不是固定顯示問號圖示了.",
			"[額外物品條] 添加更多可開啟物品.",
			"[額外物品條] 更新了實用物品分組的部分工程學物品列表. 感謝 LvWind",
			"[額外物品條] 修復了至暗之夜版本物品品質圖示不正確的問題.",
		},
		["enUS"] = {
			"[Skins] Fixed the compatibility with the latest version of World Quest Tab.",
			"[Skins] Improved the skinning of the custom anti-error tooltip from World Quest Tab by suppressing the display of the description text in it, which will adapt the skinning for Blizzard's default tooltip to the custom tooltip.",
			"[Minimap Button] Improved compatibility with the RestedXP Guides addon, which should no longer cause a blank area to appear.",
			"[Shield] Improved the display of shield textures.",
			"[Game Bar] Adjusted the default setting for middle mouse button click to teleport to Arcantina.",
			"[Game Bar] Now the icon of Random Hearthstone will show the next randomly selected hearthstone's icon instead of a fixed question mark icon.",
			"[Extra Item Bar] Added more openable items.",
			"[Extra Item Bar] Updated the list of some engineering items in UTILITY. Thanks LvWind",
			"[Extra Item Bar] Fixed the issue of incorrect item quality icons for the Midnight crafted items.",
		},
		["koKR"] = {
			"[스킨] 최신 버전의 World Quest Tab과의 호환성을 수정했습니다.",
			"[스킨] World Quest Tab의 커스텀 방지 오류 툴팁의 스킨을 개선하여 그 안에 설명 텍스트의 표시를 억제함으로써 블리자드의 기본 툴팁에 대한 스킨을 커스텀 툴팁에 적용하도록 했습니다.",
			"[미니맵 버튼] RestedXP Guides 애드온과의 호환성이 향상되어 더 이상 빈 영역이 나타나지 않습니다.",
			"[방패] 방패 텍스처의 표시가 개선되었습니다.",
			"[게임 바] 마우스 가운데 버튼 클릭의 기본 설정을 아르칸티나로 텔레포트하도록 조정했습니다.",
			"[게임 바] 이제 랜덤 하스스톤의 아이콘이 고정된 물음표 아이콘 대신 다음에 무작위로 선택된 하스스톤의 아이콘을 표시합니다.",
			"[추가 아이템 바] 더 많은 열 수 있는 아이템을 추가했습니다.",
			"[추가 아이템 바] UTILITY의 일부 공학 아이템 목록을 업데이트했습니다. 감사합니다 LvWind",
			"[추가 아이템 바] 자정 제작 아이템의 잘못된 아이템 품질 아이콘 문제를 수정했습니다.",
		},
		["ruRU"] = {
			"[Скины] Исправлена совместимость с последней версией World Quest Tab.",
			"[Скины] Улучшена обработка пользовательской подсказки от ошибок World Quest Tab путем подавления отображения текста описания в ней, что позволит адаптировать оформление подсказки Blizzard по умолчанию к пользовательской подсказке.",
			"[Кнопка миникарты] Улучшена совместимость с аддоном RestedXP Guides, который больше не должен вызывать появление пустой области.",
			"[Щит] Улучшено отображение текстур щита.",
			"[Игровая панель] Настройка по умолчанию для нажатия средней кнопки мыши изменена на телепортацию в Аркантину.",
			"[Игровая панель] Теперь иконка Случайного Камня возвращения будет показывать иконку следующего случайно выбранного камня возвращения вместо фиксированной иконки вопросительного знака.",
			"[Дополнительная панель предметов] Добавлено больше открываемых предметов.",
			"[Дополнительная панель предметов] Обновлен список некоторых инженерных предметов в UTILITY. Спасибо LvWind",
			"[Дополнительная панель предметов] Исправлена проблема с неправильными иконками качества предметов для предметов, созданных в Полуночи.",
		},
	},
}
