local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[415] = {
	RELEASE_DATE = "TBD",
	IMPORTANT = {
		["zhCN"] = {},
		["zhTW"] = {},
		["enUS"] = {},
		["koKR"] = {},
		["ruRU"] = {},
	},
	NEW = {
		["zhCN"] = {
			"新增 [战斗] - [伤害统计布局] 模块. 该模块能够帮助你快速建立多个对齐布局并根据条件自动切换. 默认关闭.",
			"新增 [任务成就] - [自动折叠] 模块. 该模块能够根据角色所在区域或者状态自动折叠或展开任务追踪框体. 默认关闭.",
			"[美化外观] 新增了 Extra Quest Button 美化外观.",
		},
		["zhTW"] = {
			"新增 [戰鬥] - [傷害統計佈局] 模組. 該模組能夠幫助你快速建立多個對齊佈局並根據條件自動切換. 預設關閉.",
			"新增 [任務成就] - [自動折疊] 模組. 該模組能夠根據角色所在區域或者狀態自動折疊或展開任務追蹤框框架. 預設關閉.",
			"[美化外觀] 新增了 Extra Quest Button 美化外觀.",
		},
		["enUS"] = {
			"Added a new module [Combat] - [Damage Meter Layout]. This module helps you quickly set up multiple aligned layouts and automatically switch between them based on conditions. Disabled by default.",
			"Added a new module [Quest & Achieve] - [Auto Collapse]. This module automatically collapses or expands the objective tracker based on the player's location or status. Disabled by default.",
			"[Skins] Added a new skin for Extra Quest Button.",
		},
		["koKR"] = {
			"[전투] - [데미지 미터 레이아웃] 모듈이 추가되었습니다. 이 모듈은 여러 정렬된 레이아웃을 빠르게 설정하고 조건에 따라 자동으로 전환하는 데 도움이 됩니다. 기본적으로 비활성화되어 있습니다.",
			"[퀘스트 & 업적] - [자동 접기] 모듈이 추가되었습니다. 이 모듈은 플레이어의 위치나 상태에 따라 목표 추적기를 자동으로 접거나 펼칩니다. 기본적으로 비활성화되어 있습니다.",
			"[스킨] Extra Quest Button에 대한 새로운 스킨이 추가되었습니다.",
		},
		["ruRU"] = {
			"Добавлен новый модуль [Бой] - [Макет счетчика урона]. Этот модуль помогает быстро настроить несколько выровненных макетов и автоматически переключаться между ними в зависимости от условий. По умолчанию отключено.",
			"Добавлен новый модуль [Задания и достижения] - [Авто-сворачивание]. Этот модуль автоматически сворачивает или разворачивает отслеживатель задач в зависимости от местоположения или статуса игрока. По умолчанию отключено.",
			"[Скины] Добавлен новый скин для Extra Quest Button.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[游戏条] 修复了点击好友列表图标有时候会变为添加好友的问题.",
			"[游戏条] 修复了有时会提示炉石无法找到的问题.",
			"[装备观察] 更新了至暗之夜中额外宝石插槽的显示逻辑.",
			"[右键菜单] 放宽污染防止策略, 现在只有在右键战网好友时才需要使用 Ctrl 来显示菜单, 其他情况下无需按住 Ctrl 键.",
			"[额外物品条] 更新了至暗之夜专业物品, 同时分离了不同版本的专业物品列表. 你可以使用 PROFTWW, PROFMN 来使用不同版本的专业物品列表.",
			"[额外物品条] 添加部分缺失的至暗之夜药水.",
			"[进度] 微调了 M+ 特殊成就的默认开启项目.",
			"[任务列表] 大幅优化了任务列表的内存占用情况.",
			"[美化外观] 优化了暴雪背包的美化外观性能问题.",
			"[美化外观] 伤害统计美化现在支持完全隐藏窗口背景了.",
			"[美化外观] 伤害统计美化现在支持调整滚动条了.",
		},
		["zhTW"] = {
			"[遊戲條] 修復了點擊好友列表圖標有時候會變為添加好友的問題.",
			"[遊戲條] 修復了有時會提示爐石無法找到的問題.",
			"[裝備觀察] 更新了至暗之夜中額外寶石插槽的顯示邏輯.",
			"[右鍵菜單] 放寬污染防止策略, 現在只有在右鍵戰網好友時才需要使用 Ctrl 來顯示菜單, 其他情況下無需按住 Ctrl 鍵.",
			"[額外物品條] 更新了至暗之夜專業物品, 同時分離了不同版本的專業物品列表. 你可以使用 PROFTWW, PROFMN 來使用不同版本的專業物品列表.",
			"[額外物品條] 添加部分缺失的至暗之夜藥水.",
			"[進度] 微調了 M+ 特殊成就的默認開啟項目.",
			"[任務列表] 大幅優化了任務列表的內存佔用情況.",
			"[美化外觀] 優化了暴雪背包的美化外觀性能問題.",
			"[美化外觀] 傷害統計美化現在支持完全隱藏視窗背景了.",
			"[美化外觀] 傷害統計美化現在支持調整滾動條了.",
		},
		["enUS"] = {
			"[Game Bar] Fixed an issue where clicking the friends list icon sometimes changed to add friend.",
			"[Game Bar] Fixed an issue where it sometimes prompts hearthstone not found.",
			"[Inspect] Updated the display logic for additional gem sockets in Midnight.",
			"[Context Menu] Relaxed the anti-taint strategy, now only requiring Ctrl to show the menu when right-clicking a Battle.net friend, and no longer requiring Ctrl for other cases.",
			"[Extra Item Bar] Updated the profession items for Midnight, and separated the profession item lists for different versions. You can use PROFTWW, PROFMN to use the profession item lists for different versions.",
			"[Extra Item Bar] Added some missing potions for Midnight.",
			"[Progress] Tweaked the default enabled M+ special achievements.",
			"[Objective Tracker] Significantly optimized the memory usage.",
			"[Skins] Optimized the skinning performance for Blizzard's bags.",
			"[Skins] The damage meter skin now supports completely hiding the window backdrop.",
			"[Skins] The damage meter skin now supports adjusting the scrollbar.",
		},
		["koKR"] = {
			"[게임 바] 친구 목록 아이콘을 클릭할 때 가끔 친구 추가로 변경되는 문제를 수정했습니다.",
			"[게임 바] 가끔 '하스스톤을 찾을 수 없습니다'라는 메시지가 표시되는 문제를 수정했습니다.",
			"[검사] 한밤중에서 추가 보석 슬롯에 대한 표시 로직을 업데이트했습니다.",
			"[컨텍스트 메뉴] 오염 방지 전략을 완화하여 이제 Battle.net 친구를 오른쪽 클릭할 때 Ctrl 키를 눌러야 메뉴가 표시되고, 다른 경우에는 Ctrl 키가 더 이상 필요하지 않습니다.",
			"[추가 아이템 바] 한밤중의 전문 아이템을 업데이트하고, 다른 버전의 전문 아이템 목록을 분리했습니다. PROFTWW, PROFMN을 사용하여 다른 버전의 전문 아이템 목록을 사용할 수 있습니다.",
			"[추가 아이템 바] 한밤중에 누락된 일부 물약을 추가했습니다.",
			"[진행 상황] M+ 특수 업적의 기본 활성 항목을 조정했습니다.",
			"[목적 추적기] 메모리 사용량을 크게 최적화했습니다.",
			"[스킨] 블리자드 가방의 스킨 성능을 최적화했습니다.",
			"[스킨] 데미지 미터 스킨이 이제 창 배경을 완전히 숨기는 것을 지원합니다.",
			"[스킨] 데미지 미터 스킨이 이제 스크롤바 조정을 지원합니다.",
		},
		["ruRU"] = {
			"[Панель игры] Исправлена проблема, из-за которой при нажатии на значок списка друзей иногда происходило добавление друга.",
			"[Панель игры] Исправлена проблема, из-за которой иногда появлялось сообщение 'Камень возвращения не найден'.",
			"[Осмотр] Обновлена логика отображения дополнительных слотов для самоцветов в 'Полночи'.",
			"[Контекстное меню] Упрощена стратегия предотвращения ошибок Blizzard. Теперь для отображения меню при ПКМ на друга в Battle.net требуется нажать Ctrl, а в других случаях Ctrl больше не требуется.",
			"[Дополнительная панель предметов] Обновлены предметы профессий для 'Полночи', а также разделены списки предметов профессий для разных версий. Вы можете использовать PROFTWW, PROFMN для использования списков профессиональных предметов для разных версий.",
			"[Дополнительная панель предметов] Добавлены некоторые отсутствующие зелья для 'Полночи'.",
			"[Прогресс] Изменены настройки специальных достижений для M+, включенных по умолчанию.",
			"[Отслеживание задач] Значительно оптимизировано использование памяти.",
			"[Скины] Оптимизирована производительность скинов для сумок Blizzard.",
			"[Скины] Скин для счетчика урона теперь поддерживает полное скрытие фона окна.",
			"[Скины] Скин для счетчика урона теперь поддерживает настройку полосы прокрутки.",
		},
	},
}
