local W, F, E, L, V, P, G = unpack(select(2, ...))

V.skins = {
	color = {
		r = 0,
		g = 0,
		b = 0,
	},
	ace3 = {
		enable = true,
	},
	blizzard = {
		enable = true,
		achievement = true,
		addonManager = true,
		adventureMap = true,
		auctionHouse = true,
		communities = true,
		character = true,
		debug = true,
		friends = true,
		garrison = true,
		help = true,
		ime = true,
		lfg = true,
		lossOfControl = true,
		macro = true,
		mail = true,
		merchant = true,
		microButtons = true,
		mirrorTimers = true,
		misc = true,
		orderHall = true,
		quest = true,
		raidInfo = true,
		raidUtility = true,
		spellBook = true,
		staticPopup = true,
		talent = true,
		tooltip = true,
		worldMap = true,
	},
	elvui = {
		enable = true,
		actionBars = true,
		actionBarsBackdrop = false,
		altPowerBar = true,
		auras = true,
		castBars = true,
		chatPanels = true,
		classBars = true,
		chatCopyFrame = true,
		dataBars = true,
		miniMap = true,
		option = true,
		panels = true,
		staticPopup = true,
		statusReport = true,
		unitFrames = true,
	},
}