local W, F, E, L, V, P, G = unpack(select(2, ...))

V.skins = {
	color = {
		r = 0,
		g = 0,
		b = 0,
	},
	ace3 = {
		enable = true,
	},
	blizzard = {
		enable = true,
		achievement = true,
		addonManager = true,
		auctionHouse = true,
		communities = true,
		character = true,
		debug = true,
		friends = true,
		garrison = true,
		ime = true,
		lfg = true,
		macro = true,
		mail = true,
		merchant = true,
		microButtons = true,
		mirrorTimers = true,
		misc = true,
		quest = true,
		spellbook = true,
		staticPopup = true,
		talent = true,
		tooltip = true,
		worldMap = true,
	},
	elvui = {
		enable = true,
		actionbar = true,
		actionbarBackdrop = false,
		altPowerBar = true,
		auras = true,
		chatCopyFrame = true,
		databars = true,
		minimap = true,
		option = true,
		panels = true,
		tooltip = true,
		staticPopup = true,
	},
}