local W, F, E, L, V, P, G = unpack(select(2, ...))

V.skins = {
	color = {
		r = 0,
		g = 0,
		b = 0,
	},
	vignetting = {
		enable = true,
		level = 30,
	},
	ace3 = {
		enable = true,
	},
	blizzard = {
		enable = true,
		achievement = true,
		addonManager = true,
		adventureMap = true,
		auctionHouse = true,
		barberShop = true,
		calendar = true,
		challenges = true,
		character = true,
		communities = true,
		debugTools = true,
		dressingRoom = true,
		friends = true,
		garrison = true,
		gossip = true,
		help = true,
		ime = true,
		lookingForGroup = true,
		loot = true,
		lossOfControl = true,
		macro = true,
		mail = true,
		merchant = true,
		microButtons = true,
		mirrorTimers = true,
		misc = true,
		orderHall = true,
		quest = true,
		raidInfo = true,
		raidUtility = true,
		scenario = true,
		spellBook = true,
		staticPopup = true,
		talent = true,
		taxi = true,
		tooltip = true,
		warboard = true,
		worldMap = true,
	},
	elvui = {
		enable = true,
		actionBarsBackdrop = true,
		actionBarsButton = true,
		afk = true,
		altPowerBar = true,
		auras = true,
		bags = true,
		castBars = true,
		chatPanels = true,
		classBars = true,
		chatCopyFrame = true,
		dataBars = true,
		miniMap = true,
		option = true,
		panels = true,
		staticPopup = true,
		statusReport = true,
		unitFrames = true,
	},
}