local W = unpack((select(2, ...)))

W.Changelog[200] = {
	RELEASE_DATE = "2020/10/13",
	IMPORTANT = {
		["zhCN"] = {
			"完全重写了全部模块和核心功能",
		},
		["zhTW"] = {
			"完全重寫了全部模組和核心功能",
		},
		["enUS"] = {
			"Completely rewrite all modules and core functions.",
		},
	},
	NEW = {
		["zhCN"] = {
			"新增游戏条功能",
			"新增静音功能",
			"新增快速钥石功能",
			"新增天赋管家功能",
			"新增右键菜单功能",
			"新增进出战斗动画功能",
			"新增小地图点击者功能",
			"新增矩形小地图功能",
			"新增快速焦点功能",
			"新增任务栏快捷开关按钮",
			"新增聊天文字修改功能",
			"新增单位框体施法条设定功能",
			"新增单位框体图标组切换功能",
			"新增幻化套装支持神器的功能",
			"新增鼠標提示生命条文字, 位置修改功能",
			"新增鼠标提示队伍信息功能",
			"新增快速感谢按钮",
			"新增 Ace3-GUI 部分 Widget 组件皮肤",
			"新增 Hekili 插件皮肤",
			"新增 Immersion 插件皮肤",
			"新增 WeakAuras_Option 插件皮肤",
			"新增 BugSack 插件皮肤",
			"新增 TinyInspect 插件皮肤",
		},
		["zhTW"] = {
			"新增遊戲條功能",
			"新增靜音功能",
			"新增快速鑰石功能",
			"新增天賦管家功能",
			"新增右鍵菜單功能",
			"新增進出戰鬥動畫功能",
			"新增小地圖點擊者功能",
			"新增矩形小地圖功能",
			"新增快速焦點功能",
			"新增任務欄快捷開關按鈕",
			"新增聊天文字修改功能",
			"新增單位框體施法條設定功能",
			"新增單位框體圖標組切換功能",
			"新增幻化套裝支持神器的功能",
			"新增浮動提示生命條文字, 位置修改功能",
			"新增浮動提示隊伍信息功能",
			"新增快速感謝按鈕",
			"新增 Ace3-GUI 部分 Widget 組件皮膚",
			"新增 Hekili 插件皮膚",
			"新增 Immersion 插件皮膚",
			"新增 WeakAuras_Option 插件皮膚",
			"新增 BugSack 插件皮膚",
			"新增 TinyInspect 插件皮膚",
		},
		["enUS"] = {
			"Add Game Bar module",
			"Add Mute module",
			"Add Quick Keystone module",
			"Add Talent Manager module",
			"Add Context Menu module",
			"Add Combat Alert module",
			"Add Rectangle Minimap module",
			"Add Quick Focus module",
			"Add Switch Button module",
			"Add Chat Text module",
			"Add customization of ElvUI cast bars",
			"Add new sets of role icons",
			"Add the support of saving artifacts in wardobe wardrobe outfits",
			"Add the feature that customizes position of health bar in the tooltip",
			"Add the feature that adding LFG group info into tooltip",
			"Add a button for saying thanks to trade target",
			"New skins for partical Ace3-GUI widgets",
			"New skins for Hekili",
			"New skins for Immersion",
			"New skins for WeakAuras_Option",
			"New skins for BugSack",
			"New skins for TinyInspect",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"更新 9.0 地图迷雾去除",
			"更新 9.0 暗影国度的大餐和技能通报",
			"更新 9.0 暗影国度的药水, 药剂等物品的自动物品列表",
			"为团队标记条添加团队确认, 倒数, 高级战斗记录开关等功能",
			"完善暴雪, ElvUI, WindTools 框体及模块的边缘美化",
			"在装备鱼竿时停用快速拾取",
			"修复 BigWigs 插件皮肤",
			"修复 WeakAuras 插件皮肤",
			"修复与 ElvUI_MerathilisUI 同时使用时可能发生的错误",
			"修复聊天链接图标中不显示天赋图标的问题",
			"修复移动框体可能造成的错误",
			"修复聊天条功能加入世界频道时可能造成的频道丢失问题",
			"修复背包空间不足时快速拾取可能导致的问题",
		},
		["zhTW"] = {
			"更新 9.0 地圖迷霧去除",
			"更新 9.0 暗影之地的大餐和技能通報",
			"更新 9.0 暗影之地的藥水, 藥劑等物品的自動物品列表",
			"為團隊標記條添加團隊確認, 倒數, 高級戰鬥記錄開關等功能",
			"完善暴雪, ElvUI, WindTools 框架及模組的邊緣美化",
			"在裝備魚竿時停用快速拾取",
			"修正 BigWigs 插件皮膚",
			"修正 WeakAuras 插件皮膚",
			"修正與 ElvUI_MerathilisUI 同時使用時可能發生的錯誤",
			"修正聊天鏈接圖標中不顯示天賦圖標的問題",
			"修正移動框體可能造成的錯誤",
			"修正聊天條功能加入世界頻道時可能造成的頻道丟失問題",
			"修正背包空間不足時快速拾取可能導致的問題",
		},
		["enUS"] = {
			"Update world map removal database to 9.0.",
			"Update feast and  utility spell IDs to 9.0",
			"Update automatic item list of potions, potions, and other items to 9.0",
			"Add ready check, countdown, toggle advanced combat logging to raid mark bar.",
			"Renew some skins of Blizzard, ElvUI, WindTools frames or modules",
			"Stop fast loot if equip any fishing pole",
			"Fix the skin for BigWigs",
			"Fix the skin for WeakAuras",
			"Fix the errors that may occur when enabling ElvUI_MerathilisUI simultaneously",
			"Fix the problem that the icon not displayed before talent links",
			"Fix the several bugs of Move Frames module",
			"Fix the auto-join of world channel",
			"Fix the problem that fast loot when bags are full",
		},
	},
}
