local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[202] = {
	RELEASE_DATE = "2020/10/20",
	IMPORTANT = {
		["zhCN"] = {
			"QQ 群号之前写错了, 正确的是: 336069019",
		},
		["zhTW"] = {
			"QQ 群號之前寫錯了, 正確的是: 336069019",
		},
		["enUS"] = {
			"I made mistake on the number of QQ Group, the correct one is 336069019.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[本地化] 修复了简体中文版本提示.",
			"[游戏条] 修复了开关游戏条可能带来的错误.",
			"[游戏条] 移除了自动垃圾收集机制.",
			"[游戏条] 仅在事件触发时更新额外文字.",
			"[游戏条] 使用 ElvUI 数据文字(时间)的鼠标提示来替换现有的提示.",
			"[游戏条] 暂时移除了 9.0 版本中的炉石.",
			"[聊天条] 修复了未设定频道名时部分按钮不显示的问题.",
			"[表情] 修复了选择窗口无法开启的错误.",
			"[好友列表] 修复了使命召唤: 现代战争 2 的图标显示.",
			"[无汉字计数] 修复了数据库错误.",
			"[追踪框体] 移除之前添加的暂时性修复方案.",
			"[切换按钮] 修复了随追踪框体显示/隐藏的功能.",
			"[美化皮肤] 修正了额外按钮的皮肤.",
			"[美化皮肤] Immersion 皮肤将不会罩住左边的数字了.",
			"[巅峰声望] 修复了 9.0 API 更新导致的错误.",
			"[聊天文字] 添加了 Lyn UI 图标包.",
			"[单位框体] 添加了 Lyn UI 图标包.",
		},
		["zhTW"] = {
			"[本地化] 修復了簡體中文版本提示.",
			"[遊戲條] 修復了開關遊戲條可能帶來的錯誤.",
			"[遊戲條] 移除了自動垃圾收集機制.",
			"[遊戲條] 僅在事件觸發時更新額外文字.",
			"[遊戲條] 使用 ElvUI 資訊文字(時間)的浮动提示來替換現有的提示.",
			"[遊戲條] 暫時移除了 9.0 版本中的爐石.",
			"[聊天條] 修復了未設定頻道名時部分按鈕不顯示的問題.",
			"[表情] 修復了選擇窗口無法開啟的錯誤.",
			"[好友列表] 修復了決勝時刻: 現代戰爭 2 的圖標顯示.",
			"[無漢字計數] 修復了數據庫錯誤.",
			"[追踪框體] 移除了之前添加的暫時性修復方案.",
			"[切換按键] 修復了隨追踪框體顯示/隱藏的功能.",
			"[美化皮膚] 修正了額外按鈕的皮膚.",
			"[美化皮膚] Immersion 皮膚將不會罩住左邊的數字了.",
			"[巔峰聲望] 修復了 9.0 API 更新導致的錯誤.",
			"[聊天文字] 添加了 Lyn UI 圖標包.",
			"[單位框體] 添加了 Lyn UI 圖標包.",
		},
		["enUS"] = {
			"[Localization] Fix the version message in zhCN translation.",
			"[Game Bar] Fix the bug occurred when player try to toggle the game bar.",
			"[Game Bar] Remove the auto garbage collection.",
			"[Game Bar] The additional text only be updated on event fired.",
			"[Game Bar] Use ElvUI Time data text tooltip instead of the old one.",
			"[Game Bar] Disable Hearthstones from Shadowlands temporarily.",
			"[Chat Bar] Fix the bug that several buttons do not show if the name of world channel not be set.",
			"[Emote] Fix the bug that the selector cannot be shown.",
			"[Friend List] Fix the icon of COD MW2.",
			"[No Kanji Math] Fix the database error.",
			"[Objective Tracker] Remove the temp fix.",
			"[Switch Button] Fix the auto-hide with Objective Tracker.",
			"[Skins] Change the skin of Extra Action Bar.",
			"[Skins] Immersion Skin will not hide the number anymore.",
			"[Paragon Reputation] Fix the API usage for 9.0.",
			"[Chat Text] Add Lyn UI icon pack.",
			"[UnitFrames] Add Lyn UI icon pack.",
		},
	},
}
