local W = unpack((select(2, ...)))

W.Changelog[214] = {
	RELEASE_DATE = "2020/12/07",
	IMPORTANT = {
		["zhCN"] = {},
		["zhTW"] = {},
		["enUS"] = {},
		["koKR"] = {},
	},
	NEW = {
		["zhCN"] = {
			"[额外物品条] 添加了塔内坐骑.",
			'[额外物品条] 添加了 "FOODVENDOR" (商人食物) 物品分类.',
			"[静音] 添加了布兰契的选项.",
		},
		["zhTW"] = {
			"[額外物品條] 新增了塔內坐騎.",
			'[額外物品條] 新增了 "FOODVENDOR" (商人食物) 物品分組.',
			"[靜音] 新增了布蘭契的選項.",
		},
		["enUS"] = {
			"[Extra Item Bar] Add the mount in Torghast.",
			'[Extra Item Bar] Add new item group "FOODVENDOR" (food sold by vendors).',
			"[Mute] Add an option for Blanchy.",
		},
		["koKR"] = {
			"[아이템 바] 토르가스트 탈것 추가",
			'[아이템 바] 새로운 아이템 그룹 "FOODVENDOR" (상인 판매 음식) 추가',
			"[음소거] 블랑쉬에 관한 옵션을 추가하였습니다.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[团队标记] 现在可以对调正常点击和修饰键点击的功能了.",
			"[进度] 修复了赤红深渊的传奇击杀次数统计.",
			"[额外物品条] 修复了设定时鼠标提示中法师制作食物的文本.",
			"[美化皮肤] 优化了小宠物鼠标提示的美化.",
			"[美化皮肤] 优化了 LFD 准备提示的美化.",
			"[美化皮肤] 修复了盟约任务完成提示框体图标不显示的错误.",
			"[聊天条] 修复了一个潛在的报错.",
			"[交接] 修复了一个潛在的报错.",
			"[游戏条] 现在可以设定家按钮为虫洞发生器了.",
			"[跳过过场动画] 等级 60 的人物进入噬渊将不再提示无法跳过.",
		},
		["zhTW"] = {
			"[團隊標記] 現在可以對調正常點擊和修飾鍵點擊的功能了.",
			"[進度] 修復了血紅深淵的傳奇擊殺次數統計.",
			"[額外物品條] 修復了設定時浮動提示中法師製造食物的文字.",
			"[美化皮膚] 優化了小寵物浮動提示的美化.",
			"[美化皮膚] 優化了 LFD 準備提示的美化.",
			"[美化皮膚] 修復了誓盟任務完成提示框架圖示不顯示的錯誤.",
			"[聊天條] 修復了一個潛在的錯誤.",
			"[交接] 修復了一個潛在的錯誤.",
			"[遊戲條] 現在可以設定按鈕為蟲洞產生器了.",
			"[跳過過場動畫] 等級 60 的人物進入淵吼時將不再提示無法跳過.",
		},
		["enUS"] = {
			"[Raid Marker] Now you can swap the functionality of normal click and click with modifier keys.",
			"[Progression] Fix the statastic of Sanguine Depths.",
			"[Extra Item Bar] Fix the text of food crafted by mage in item group tooltips.",
			"[Skins] Optimize the skins on Pet Tooltip.",
			"[Skins] Optimize the skins on LFD Ready Popup.",
			"[Skins] Fix the icon in misson complate alerts.",
			"[Chat Bar] Fix a potential bug.",
			"[Turn In] Fix a potential bug.",
			"[Game Bar] You can set Home button to wormhole generators now.",
			"[Skip Cut Scene] The message will not show when level 60 character entering The Maw.",
		},
		["koKR"] = {
			"[공격대 징표] 이제 일반 클릭과 기능키와 함께 클릭할 때의 기능을 전환할 수 있습니다.",
			"[진행 상태] 핏빛 심연의 통계치를 수정합니다.",
			"[아이템 바] 아이템 그룹 툴팁에서 마법사 창조 음식 텍스트를 수정했습니다.",
			"[스킨] 펫 툴팁 최적화.",
			"[스킨] 던전 찾기 준비 확인 팝업 스킨 최적화.",
			"[스킨] 성약단 임무 완료 시 상자 아이콘이 표시되지 않는 현상을 수정하였습니다.",
			"[채팅 바] 잠재적인 버그를 수정하였습니다.",
			"[자동 수락] 잠재적인 버그를 수정하였습니다.",
			"[게임 바] 이제 홈 버튼을 웜홀 생성기로 설정할 수 있습니다.",
			"[컷신 건너뛰기] 60 레벨 캐릭터는 나락에 들어갈 때 건너뛸 수 없다는 메시지가 표시되지 않습니다.",
		},
	},
}
