local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[215] = {
	RELEASE_DATE = "2020/12/18",
	IMPORTANT = {
		["zhCN"] = {},
		["zhTW"] = {},
		["enUS"] = {},
		["koKR"] = {},
	},
	NEW = {
		["zhCN"] = {
			"[其他] 添加了隐藏制造者姓名的功能及选项.",
			"[美化皮肤] 添加了每周奖励宝库的界面美化.",
			"[副本难度] 添加了一个文字对齐选项.",
		},
		["zhTW"] = {
			"[其他] 新增了隱藏製作者姓名的功能及設定.",
			"[美化皮膚] 新增了每週獎勵寶庫的界面美化.",
			"[副本難度] 新增了一個文字對齊選項.",
		},
		["enUS"] = {
			"[Misc] Add new feature and option of hiding crafter name.",
			"[Skins] Add skin for weekly rewards.",
			"[Instance Difficulty] Add a new option of text-align.",
		},
		["koKR"] = {
			"[기타] 제작 아이템의 제작자 이름을 숨겨주는 새로운 옵션을 추가하였습니다.",
			"[스킨] 주간 보상(위대한 금고) 스킨 추가.",
			"[인스턴스 난이도] 텍스트 정렬 옵션을 추가하였습니다.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"修正了一些之前更新记录的文本.",
			"[通告] 修复了在离队后可能出现的错误.",
			"[通告] 添加了永恒药锅. 感谢 Seiryuu-sama",
			"[游戏条] 右键冒险手册现在将会打开每周奖励宝库.",
			"[游戏条] 炉石列表新增温西尔罪碑.",
			"[移动框体] 添加了每周奖励宝库界面的支持.",
			"[美化皮肤] 修复了团队工具皮肤可能造成的错误.",
			"[美化皮肤] 优化了史诗钥石界面美化.",
			"[额外物品条] UTILITY (实用工具) 分组新增了护甲片等暗影国度制作物品.",
			"[额外物品条] 更新托加斯特物品列表.",
			"[观察] 修复了暗影国度的附魔信息. 感谢 loudsoul",
			"[团队进度] 修复了副本进度获取错误的问题.",
		},
		["zhTW"] = {
			"修正了一些之前的更新記錄的文本.",
			"[通告] 修復了可能出現的離隊後錯誤.",
			"[通告] 新增了永恆大鍋. 感謝 Seiryuu-sama",
			"[遊戲條] 右鍵地城導覽手冊按鍵現在將會開啟每週獎勵寶庫.",
			"[遊戲條] 爐石列表新增汎希爾罪孽石.",
			"[移動框架] 支援每週獎勵寶庫介面.",
			"[美化皮膚] 修復了團隊工具皮膚可能造成的錯誤.",
			"[美化皮膚] 優化了傳奇鑰石介面美化.",
			"[額外物品條] UTILITY (實用工具) 分組新增了護甲片等暗影之境製造物品.",
			"[額外物品條] 更新托伽司物品列表.",
			"[觀察] 修復了暗影之境的附魔訊息. 感謝 loudsoul",
			"[團隊進度] 修復了副本進度獲取錯誤的問題.",
		},
		["enUS"] = {
			"Amend some parts of the previous changelog.",
			"[Announcement] Fix the bug that may occur after leaving from a group.",
			"[Announcement] Add Eternal Cauldron. Thanks Seiryuu-sama",
			"[Game Bar] Right-click Encounter Journal button now will open Weekly Rewards.",
			"[Game Bar] Add Venthyr Sinstone to Hearthstone list.",
			"[Move Frame] Add support for weekly rewards.",
			"[Skins] Fix a potential bug of Raid Utility skin.",
			"[Skins] Optimize Mythic Dungeon Keystone skin.",
			"[Extra Item Bar] UTILITY (utilities) category add some Shadowlands crafting items like armor kit.",
			"[Extra Item Bar] Update Torghast item list.",
			"[Inpect] Fix the Shadowlands enchant info. Thanks loudsoul.",
			"[Progression] Update Boss IDs for fetching progression correctly.",
		},
		["koKR"] = {
			"이전 변경 로그의 일부 수정.",
			"[알림] 파티를 떠난 후 발생할 수 있는 오류를 수정하였습니다.",
			"[알림] 영원의 가마솥을 추가하였습니다. Thanks Seiryuu-sama",
			"[게임 바] 모험 안내서를 마우스 오른쪽 버튼으로 클릭하면 주간 보상 금고를 확인할 수 있습니다.",
			"[게임 바] 베나리의 이동의 암호를 귀환석 리스트에 추가하였습니다.",
			"[프레임 이동] 주간 보상 (위대한 금고) 창을 이동할 수 있습니다.",
			"[스킨] 공격대 도구 스킨의 잠재적인 버그를 수정하였습니다.",
			"[스킨] 쐐기던전의 쐐기돌 스킨을 최적화하였습니다.",
			"[아이템 바] UTILITY (유틸리티) 카테고리에 방어구 강화, 기름, 숫돌 같은 어둠땅 제작 아이템이 추가 되였습니다.",
			"[아이템 바] 토르가스트 아이템 리스트 업데이트.",
			"[살펴보기] 어둠땅 마법 부여 정보를 수정하였습니다. Thanks loudsoul.",
			"[진행 상태] 진행 상황을 올바르게 가져오기 위해 보스ID를 업데이트 하였습니다.",
		},
	},
}
