local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[409] = {
	RELEASE_DATE = "2026/01/31",
	IMPORTANT = {
		["zhCN"] = {
			"继续优化至暗之夜 API 改动带来的兼容性问题.",
			"[右键菜单] 由于暴雪的「查看住宅」按钮污染问题, 现在只有在你按住 Shift 键的同时右键点击时才会添加额外选项.",
			"[高级] - [至暗之夜 API 修复] 由于暴雪已经修复了 MoneyFrame 相关错误, 移除了相关的修复补丁.",
			"[高级] 由于暴雪API改动, 功能不再能够实现, 移除了战斗日志增强功能.",
			"[其他] - [冷却文字偏移] 由于 ElvUI 新的冷却文字已经支持偏移功能, 移除了该功能模块.",
			"[标签] 完全重构了标签模块, 并移动到了单位框体分类. 你可以在 [单位框体] - [标签] 中找到新的可适用于新版 ElvUI 单位框体的标签.",
			"[吸收] 该模块现在支持最新版 ElvUI 单位框体.",
			"[单位框体] 该模块现在支持最新版 ElvUI 单位框体.",
			"[其他] - [快捷键文字置顶] 该功能现在支持最新版 ElvUI 动作条.",
			"[其他] - [CVars 编辑器] 清理了旧 CVars 选项, 并新增了一些常用的新 CVars 参数选项.",
		},
		["zhTW"] = {
			"繼續優化至暗之夜 API 改動帶來的相容性問題.",
			"[右鍵選單] 由於暴雪的「查看家宅」按鈕污染問題, 現在只有在你按住 Shift 鍵的同時右鍵點擊時才會添加額外選項.",
			"[高級] - [至暗之夜 API 修復] 由於暴雪已經修復了 MoneyFrame 相關錯誤, 移除了相關的修復補丁.",
			"[進階] 由於暴雪API改動, 功能不再能夠實現, 移除了戰鬥日誌增強功能.",
			"[其他] - [冷卻文字偏移] 由於 ElvUI 新的冷卻文字已經支援偏移功能, 移除了該功能模組.",
			"[標籤] 完全重構了標籤模組, 並移動到了單位框架分類. 你可以在 [單位框架] - [標籤] 中找到新的可適用於新版 ElvUI 單位框體的標籤.",
			"[吸收] 該模組現在支援最新版 ElvUI 單位框架",
			"[單位框架] 該模組現在支援最新版 ElvUI 單位框架.",
			"[其他] - [按鍵綁定文字置頂] 該功能現在支援最新版 ElvUI 快捷列.",
			"[其他] - [CVars 編輯器] 清理了舊 CVars 選項, 並新增了一些常用的新 CVars 參數選項.",
		},
		["enUS"] = {
			"Continued to optimize compatibility issues caused by Midnight API changes.",
			"[Right-Click Menu] Because of Blizzard 'Visit Home' button taint issue, the additional options only will be added when you pressing Shift key while right-clicking.",
			"[Advanced] - [Midnight API Fixes] Since Blizzard has fixed the MoneyFrame related bugs, the related fix patches have been removed.",
			"[Advanced] The combat log enhancement feature has been removed due to Blizzard API changes making the feature no longer feasible.",
			"[Misc] - [Cooldown Text Offset] This feature module has been removed as the new ElvUI cooldown text already supports offset functionality.",
			"[Tags] Completely rebuilt the module, and move it to the Unit Frames category. You can find the new tags applicable to the new ElvUI unit frames in [Unit Frames] - [Tags].",
			"[Absorb] This module now supports the latest ElvUI unit frames.",
			"[Unit Frames] This module now supports the latest ElvUI unit frames.",
			"[Misc] - [Keybind Text Above] This feature now supports the latest ElvUI action bars.",
			"[Misc] - [CVars Editor] Cleaned up old CVars options and added some commonly used new CVars parameter options.",
		},
		["koKR"] = {
			"미드나이트 API 변경으로 인한 호환성 문제를 지속적으로 최적화했습니다.",
			"[오른쪽 클릭 메뉴] 블리자드 '주택 방문' 버튼 오염 문제로 인해 Shift 키를 누른 상태에서 오른쪽 클릭할 때만 추가 옵션이 추가됩니다.",
			"[고급] - [미드나이트 API 수정] 블리자드가 MoneyFrame 관련 버그를 수정했으므로 관련 수정 패치를 제거했습니다.",
			"[고급] 전투 로그 향상 기능은 블리자드 API 변경으로 인해 더 이상 실행할 수 없게 되어 제거되었습니다.",
			"[기타] - [재사용 대기시간 텍스트 오프셋] 새로운 ElvUI 재사용 대기시간 텍스트가 이미 오프셋 기능을 지원하므로 이 기능 모듈이 제거되었습니다.",
			"[태그] 모듈이 완전히 재구성되었으며, 유닛 프레임 범주로 이동되었습니다. 새로운 ElvUI 유닛 프레임에 적용할 수 있는 새로운 태그는 [유닛 프레임] - [태그]에서 찾을 수 있습니다.",
			"[흡수] 이 모듈은 이제 최신 ElvUI 유닛 프레임을 지원합니다.",
			"[유닛 프레임] 이 모듈은 이제 최신 ElvUI 유닛 프레임을 지원합니다.",
			"[기타] - [단축키 텍스트 위] 이 기능은 이제 최신 ElvUI 행동 막대를 지원합니다.",
			"[기타] - [CVars 편집기] 이전 CVars 옵션을 정리하고 일반적으로 사용되는 새로운 CVars 매개변수 옵션을 추가했습니다.",
		},
		["ruRU"] = {
			"Продолжена оптимизация проблем совместимости, вызванных изменениями API Полуночи.",
			"[Меню правой кнопки мыши] Из-за проблемы с отображением кнопки 'Посетить дом' от Blizzard дополнительные параметры будут добавлены только при нажатии клавиши Shift во время щелчка ПКМ.",
			"[Расширенные] - [Исправления API Полуночи] Поскольку Blizzard исправила связанные с MoneyFrame ошибки, соответствующие исправляющие патчи были удалены.",
			"[Расширенные] Функция улучшения журнала боевых действий была удалена из-за изменений API Blizzard, которые сделали эту функцию невозможной.",
			"[Разное] - [Смещение текста перезарядки] Этот модуль функции был удален, поскольку новый текст перезарядки ElvUI уже поддерживает функцию смещения.",
			"[Теги] Модуль был полностью перестроен, и перемещен в категорию 'Фреймы юнитов'. Новые теги, применимые к новым фреймам юнитов ElvUI, можно найти в разделе [Фреймы юнитов] - [Теги].",
			"[Поглощение] Этот модуль теперь поддерживает актуальные фреймы юнитов ElvUI.",
			"[Фреймы юнитов] Этот модуль теперь поддерживает актуальные фреймы юнитов ElvUI.",
			"[Разное] - [Текст привязки клавиш сверху] Эта функция теперь поддерживает актуальные панели действий ElvUI.",
			"[Разное] - [Редактор CVars] Были очищены старые параметры CVars и добавлены некоторые часто используемые новые параметры CVars.",
		},
	},
	NEW = {
		["zhCN"] = {
			"[智能 Tab] 新增一个选项可以在切换循环中加入 [聊天条] 模块中设定的世界频道. 默认关闭.",
			"[进度] 新增一个选项可以只显示观察对象已经完成的特殊成就而不是全部显示. 默认开启.",
			"[进度] 新增一个选项可以调整特殊成就的显示顺序, 可选择按资料片或难度排序.",
		},
		["zhTW"] = {
			"[智能 Tab] 新增一個選項可以在切換循環中加入 [聊天條] 模組中設定的世界頻道. 預設關閉.",
			"[進度] 新增一個選項可以只顯示觀察對象已經完成的特殊成就而不是全部顯示. 預設開啟.",
			"[進度] 新增一個選項可以調整特殊成就的顯示順序, 可選擇按資料片或難度排序.",
		},
		["enUS"] = {
			"[Smart Tab] Added an option to include the world channel set in the [Chat Bar] module in the switch cycle. Disabled by default.",
			"[Progression] Added an option to only show the special achievements that the inspected target has completed instead of showing all. Enabled by default.",
			"[Progression] Added an option to adjust the display order of special achievements, allowing sorting by expansion or difficulty.",
		},
		["koKR"] = {
			"[스마트 탭] 전환 주기에 [채팅 바] 모듈에 설정된 월드 채널을 포함하는 옵션이 추가되었습니다. 기본적으로 비활성화되어 있습니다.",
			"[진행 상황] 검사 대상이 완료한 특별 업적만 표시하는 옵션이 추가되었습니다. 기본적으로 활성화되어 있습니다.",
			"[진행 상황] 특별 업적의 표시 순서를 조정하는 옵션이 추가되었습니다. 확장 또는 난이도별로 정렬할 수 있습니다.",
		},
		["ruRU"] = {
			"[Умная вкладка] Добавлена опция для включения мирового канала, установленного в модуле [Панель чата], в цикл переключения. По умолчанию отключено.",
			"[Прогресс] Добавлена опция для отображения только специальных достижений, которые завершил проверяемый объект, вместо отображения всех. По умолчанию включено.",
			"[Прогресс] Добавлена опция для настройки порядка отображения специальных достижений с возможностью сортировки по дополнению или сложности.",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[世界地图] 迷雾去除功能现在支持至暗之夜地图.",
			"[额外物品条] 移除了 SL 和 DF 相关的物品条组别, 并新增了至暗之夜相关的物品条组别.",
			"[额外物品条] 更新了默认的物品条设置, 同时支持地心之战和至暗之夜的物品显示.",
			"[进度] 加入了从巨龙时代到至暗之夜全部的赛季成就数据.",
			"[进度] 移除了地心之战除欧米伽以外所有的旧 Raid 进度数据, 加入了至暗之夜 3 个新 Raid 数据.",
			"[快速焦点] 现在会正确使用设定中的鼠标按钮.",
			"[事件追踪器] 考虑到之后更多的事件, 优化了事件追踪器的设置界面, 现在可以按照资料片来管理事件显示.",
			"[观察] 修复了观察其他玩家时获取装备信息失败的问题.",
			"[游戏条] 修复了更改按钮功能后, 实际的按钮功能没有正确更新的问题.",
			"[矩形小地图] 修复了一个在切换配置时可能导致的错误.",
		},
		["zhTW"] = {
			"[世界地圖] 迷霧移除功能現在支援至暗之夜地圖.",
			"[額外物品條] 移除了 SL 和 DF 相關的物品條組別, 並新增了至暗之夜相關的物品條組別.",
			"[額外物品條] 更新了預設的物品條設置, 同時支援地心之戰和至暗之夜的物品顯示.",
			"[進度] 加入了從巨龍時代到至暗之夜全部的賽季成就數據.",
			"[進度] 移除了地心之戰除歐米伽以外所有的舊 Raid 進度數據, 加入了至暗之夜 3 個新 Raid 數據.",
			"[快速焦點] 現在會正確使用設定中的滑鼠按鍵.",
			"[事件追蹤器] 考慮到之後更多的事件, 優化了事件追蹤器的設置介面, 現在可以按照資料片來管理事件顯示.",
			"[觀察] 修復了觀察其他玩家時獲取裝備資訊失敗的問題.",
			"[遊戲條] 修復了更改按鍵功能後, 實際的按鍵功能沒有正確更新的問題.",
			"[矩形小地圖] 修復了一個在切換配置時可能導致的錯誤.",
		},
		["enUS"] = {
			"[World Map] The fog removal feature now supports the Midnight map.",
			"[Extra Item Bar] Removed SL and DF related categories, and added categories related to Midnight.",
			"[Extra Item Bar] Updated the default item bar settings to support items from The War Within and Midnight.",
			"[Progression] Added season achievement data from Dragonflight to Midnight.",
			"[Progression] Removed all old raid progress data from The War Within except for Omega, and added data for 3 new raids from Midnight.",
			"[Quick Focus] Now correctly uses the mouse button set in the settings.",
			"[Event Tracker] Considering more events in the future, optimized the settings interface of the event tracker, now you can manage event display by expansion.",
			"[Inspect] Fixed an issue where equipment information failed to be obtained when inspecting other players.",
			"[Game Bar] Fixed an issue where the actual button function did not update correctly after changing the button function.",
			"[Game Bar] Fixed an issue where housing-related buttons could not be used normally after opening the friends frame using the friends button.",
			"[Rectangle Minimap] Fixed a potential error when switching profiles.",
		},
		["koKR"] = {
			"[세계 지도] 안개 제거 기능이 이제 미드나이트 지도를 지원합니다.",
			"[추가 아이템 바] SL 및 DF 관련 카테고리를 제거하고 미드나이트 관련 카테고리를 추가했습니다.",
			"[추가 아이템 바] 기본 아이템 바 설정을 업데이트하여 '내부의 전쟁' 및 '미드나이트'의 아이템을 지원합니다.",
			"[진행 상황] 드래곤플라이트부터 미드나이트까지 모든 시즌 업적 데이터를 추가했습니다.",
			"[진행 상황] '내부의 전쟁'에서 오메가를 제외한 모든 이전 공격대 진행 데이터를 제거하고 '미드나이트'의 3개의 새로운 공격대 데이터를 추가했습니다.",
			"[빠른 집중] 이제 설정에서 설정한 마우스 버튼을 올바르게 사용합니다.",
			"[이벤트 추적기] 향후 더 많은 이벤트를 고려하여 이벤트 추적기의 설정 인터페이스를 최적화했으며 이제 확장별로 이벤트 표시를 관리할 수 있습니다.",
			"[검사] 다른 플레이어를 검사할 때 장비 정보를 가져오지 못하는 문제를 수정했습니다.",
			"[게임 바] 버튼 기능을 변경한 후 실제 버튼 기능이 올바르게 업데이트되지 않는 문제를 수정했습니다.",
			"[사각 미니맵] 프로필 전환 시 발생할 수 있는 잠재적인 오류를 수정했습니다.",
		},
		["ruRU"] = {
			"[Карта мира] Функция удаления тумана теперь поддерживает карту Полуночи.",
			"[Дополнительная панель предметов] Удалены категории, связанные с SL и DF, и добавлены категории, связанные с Полуночью.",
			"[Дополнительная панель предметов] Обновлены настройки панели предметов по умолчанию для поддержки предметов из Войны внутри и Полуночи.",
			"[Прогресс] Добавлены данные о сезонных достижениях от Эпохи Драконов до Полуночи.",
			"[Прогресс] Удалены все старые данные о прогрессе рейдов из Войны внутри, кроме Омеги, добавлены данные о 3 новых рейдах из Полуночи.",
			"[Быстрый фокус] Теперь правильно используется кнопка мыши, установленная в настройках.",
			"[Трекер событий] С учетом большего количества событий в будущем оптимизирован интерфейс настроек трекера событий, теперь Вы можете управлять отображением событий по расширениям.",
			"[Осмотр] Исправлена проблема, из-за которой не удавалось получить информацию об экипировке при осмотре других игроков.",
			"[Игровая панель] Исправлена ​​ошибка, из-за которой фактическая функция кнопки некорректно обновлялась после изменения функции кнопки.",
			"[Прямоугольная миникарта] Исправлена ​​потенциальная ошибка при переключении профилей.",
		},
	},
}
