local W = unpack((select(2, ...))) ---@type WindTools

W.Changelog[415] = {
	RELEASE_DATE = "2026/03/14",
	IMPORTANT = {
		["zhCN"] = {
			"继续优化插件的稳定性, 改善对秘密值的数据的处理模式.",
		},
		["zhTW"] = {
			"繼續優化插件的穩定性, 改善對秘密值的數據的處理模式.",
		},
		["enUS"] = {
			"Continue to optimize the stability of the plugin and improve the processing of secret values.",
		},
		["koKR"] = {
			"플러그인의 안정성을 개선하고 비밀 값의 데이터 처리를 개선합니다.",
		},
		["ruRU"] = {
			"Повышена стабильность плагина и улучшена обработка секретных значений.",
		},
	},
	NEW = {
		["zhCN"] = {
			"新增 [战斗] - [伤害统计布局] 模块. 该模块能够帮助你快速建立多个对齐布局并根据条件自动切换. 默认关闭.",
			"新增 [任务成就] - [自动折叠] 模块. 该模块能够根据角色所在区域或者状态自动折叠或展开任务追踪框体. 默认关闭.",
			"新增 [任务成就] - [怪物狩猎] 模块. 该模块能够在默认的进度 UI 上显示具体进度文字, 并在进行狩猎时自动追踪相关任务. 计划今后添加更多实用功能. 默认开启.",
			"[美化外观] 新增了 Extra Quest Button 美化外观.  感谢 Dack",
			"[美化外观] 新增了 Addon Profiler 美化外观. 感谢 Dack",
		},
		["zhTW"] = {
			"新增 [戰鬥] - [傷害統計佈局] 模組. 該模組能夠幫助你快速建立多個對齊佈局並根據條件自動切換. 預設關閉.",
			"新增 [任務成就] - [自動折疊] 模組. 該模組能夠根據角色所在區域或者狀態自動折疊或展開任務追蹤框框架. 預設關閉.",
			"新增 [任務成就] - [怪物狩獵] 模組. 該模組能夠在預設的進度 UI 上顯示具體進度文字, 並在進行狩獵時自動追蹤相關任務. 計劃今後添加更多實用功能. 預設開啟.",
			"[美化外觀] 新增了 Extra Quest Button 美化外觀. 感謝 Dack",
			"[美化外觀] 新增了 Addon Profiler 美化外觀. 感謝 Dack",
		},
		["enUS"] = {
			"Added a new module [Combat] - [Damage Meter Layout]. This module helps you quickly set up multiple aligned layouts and automatically switch between them based on conditions. Disabled by default.",
			"Added a new module [Quest & Achieve] - [Auto Collapse]. This module automatically collapses or expands the objective tracker based on the player's location or status. Disabled by default.",
			"Added a new module [Quest & Achieve] - [Prey Hunt]. This module can display specific progress text on the default progress UI, and automatically track related quests when hunting. More practical features are planned to be added in the future. Enabled by default.",
			"[Skins] Added a new skin for Extra Quest Button. Thanks to Dack",
			"[Skins] Added a new skin for Addon Profiler. Thanks to Dack",
		},
		["koKR"] = {
			"[전투] - [데미지 미터 레이아웃] 모듈이 추가되었습니다. 이 모듈은 여러 정렬된 레이아웃을 빠르게 설정하고 조건에 따라 자동으로 전환하는 데 도움이 됩니다. 기본적으로 비활성화되어 있습니다.",
			"[퀘스트 & 업적] - [자동 접기] 모듈이 추가되었습니다. 이 모듈은 플레이어의 위치나 상태에 따라 목표 추적기를 자동으로 접거나 펼칩니다. 기본적으로 비활성화되어 있습니다.",
			"[퀘스트 & 업적] - [사냥감 사냥] 모듈이 추가되었습니다. 이 모듈은 기본 진행 UI에 특정 진행 텍스트를 표시할 수 있으며, 사냥을 할 때 관련 퀘스트를 자동으로 추적합니다. 앞으로 더 많은 실용적인 기능이 추가될 예정입니다. 기본적으로 활성화되어 있습니다.",
			"[스킨] Extra Quest Button에 대한 새로운 스킨이 추가되었습니다. Dack에게 감사드립니다.",
			"[스킨] Addon Profiler에 대한 새로운 스킨이 추가되었습니다. Dack에게 감사드립니다.",
		},
		["ruRU"] = {
			"Добавлен новый модуль [Бой] - [Макет счетчика урона]. Этот модуль помогает быстро настроить несколько выровненных макетов и автоматически переключаться между ними в зависимости от условий. По умолчанию отключено.",
			"Добавлен новый модуль [Задания и достижения] - [Автосворачивание]. Этот модуль автоматически сворачивает или разворачивает отслеживатель задач в зависимости от местоположения или статуса игрока. По умолчанию отключено.",
			"Добавлен новый модуль [Задания и достижения] - [Охота на добычу]. Этот модуль может отображать конкретный текст прогресса на стандартном интерфейсе прогресса и автоматически отслеживать связанные задания при охоте. В будущем планируется добавить больше практических функций. По умолчанию включено.",
			"[Скины] Добавлен новый скин для Extra Quest Button. Спасибо Dack",
			"[Скины] Добавлен новый скин для Addon Profiler. Спасибо Dack",
		},
	},
	IMPROVEMENT = {
		["zhCN"] = {
			"[任务列表] 大幅优化了任务列表的内存占用情况.",
			"[任务进度] 优化了制造业等级图标在进度中显示为乱码的问题.",
			"[游戏条] 修复了点击好友列表图标有时候会变为添加好友的问题.",
			"[游戏条] 修复了有时会提示炉石无法找到的问题.",
			"[装备观察] 更新了至暗之夜中额外宝石插槽的显示逻辑.",
			"[右键菜单] 放宽污染防止策略, 现在只有在右键战网好友时才需要使用 Ctrl 来显示菜单, 其他情况下无需按住 Ctrl 键.",
			"[额外物品条] 更新了至暗之夜专业物品, 同时分离了不同版本的专业物品列表. 你可以使用 PROFTWW, PROFMN 来使用不同版本的专业物品列表.",
			"[额外物品条] 添加部分缺失的至暗之夜药水. 感谢 Perseco.",
			"[鼠标提示] - [进度] 微调了 M+ 特殊成就的默认开启项目.",
			"[事件追踪器] 更新任务 ID, 现在识别会更加的准确.",
			"[美化外观] 优化了暴雪背包的美化外观性能问题.",
			"[美化外观] 伤害统计美化现在支持完全隐藏窗口背景了.",
			"[美化外观] 伤害统计美化现在支持调整滚动条了.",
			"[美化外观] 优化了组件皮肤, 支持更多进度条. 感谢 Dack.",
			"[美化外观] 组件皮肤在美化状态条时现在会尝试使用接近原先色彩的颜色.",
			"[美化外观] 修复了场景战役皮肤可能导致部分时间条不显示的问题.",
			"[美化外观] 优化了 BigWigs 皮肤, 支持 BigWigs 自建鼠标提示美化.",
		},
		["zhTW"] = {
			"[任務列表] 大幅優化了任務列表的內存佔用情況.",
			"[任務進度] 優化了製造業等級圖標在進度中顯示為亂碼的問題.",
			"[遊戲條] 修復了點擊好友列表圖標有時候會變為添加好友的問題.",
			"[遊戲條] 修復了有時會提示爐石無法找到的問題.",
			"[裝備觀察] 更新了至暗之夜中額外寶石插槽的顯示邏輯.",
			"[右鍵菜單] 放寬污染防止策略, 現在只有在右鍵戰網好友時才需要使用 Ctrl 來顯示菜單, 其他情況下無需按住 Ctrl 鍵.",
			"[額外物品條] 更新了至暗之夜專業物品, 同時分離了不同版本的專業物品列表. 你可以使用 PROFTWW, PROFMN 來使用不同版本的專業物品列表.",
			"[額外物品條] 添加部分缺失的至暗之夜藥水. 感謝 Perseco.",
			"[浮動提示] - [進度] 微調了 M+ 特殊成就的預設開啟項目.",
			"[事件追蹤器] 更新任務 ID, 現在識別會更加的準確.",
			"[美化外觀] 優化了暴雪背包的美化外觀性能問題.",
			"[美化外觀] 傷害統計美化現在支持完全隱藏視窗背景了.",
			"[美化外觀] 傷害統計美化現在支持調整滾動條了.",
			"[美化外觀] 優化了組件皮膚, 支持更多進度條. 感謝 Dack.",
			"[美化外觀] 組件皮膚在美化狀態條時現在會嘗試使用接近原先色彩的顏色.",
			"[美化外觀] 修復了場景戰役皮膚可能導致部分時間條不顯示的問題.",
			"[美化外觀] 優化了 BigWigs 皮膚, 支持 BigWigs 自建浮動提示美化.",
		},
		["enUS"] = {
			"[Objective Tracker] Significantly optimized the memory usage.",
			"[Quest Progress] Optimized the issue where the profession tier icons show as garbled text in the progress.",
			"[Game Bar] Fixed an issue where clicking the friends list icon sometimes changed to add friend.",
			"[Game Bar] Fixed an issue where it sometimes prompts hearthstone not found.",
			"[Inspect] Updated the display logic for additional gem sockets in Midnight.",
			"[Context Menu] Relaxed the anti-taint strategy, now only requiring Ctrl to show the menu when right-clicking a Battle.net friend, and no longer requiring Ctrl for other cases.",
			"[Extra Item Bar] Updated the profession items for Midnight, and separated the profession item lists for different versions. You can use PROFTWW, PROFMN to use the profession item lists for different versions.",
			"[Extra Item Bar] Added some missing potions for Midnight. Thanks to Perseco.",
			"[Tooltip] - [Progress] Tweaked the default enabled M+ special achievements.",
			"[Objective Tracker] Updated quest IDs, now the recognition will be more accurate.",
			"[Skins] Optimized the skinning performance for Blizzard's bags.",
			"[Skins] The damage meter skin now supports completely hiding the window backdrop.",
			"[Skins] The damage meter skin now supports adjusting the scrollbar.",
			"[Skins] Optimized the skinning for widgets, supporting more progress bars. Thanks to Dack.",
			"[Skins] The widget skin now attempts to use colors close to the original when skinning status bars.",
			"[Skins] Fixed an issue where the scenario campaign skin may cause some timer bars to not show.",
			"[Skins] Optimized the BigWigs skin, supporting BigWigs built-in tooltip skinning.",
		},
		["koKR"] = {
			"[목적 추적기] 메모리 사용량을 크게 최적화했습니다.",
			"[퀘스트 진행] 진행 상황에서 전문 레벨 아이콘이 깨진 텍스트로 표시되는 문제를 최적화했습니다.",
			"[게임 바] 친구 목록 아이콘을 클릭할 때 가끔 친구 추가로 변경되는 문제를 수정했습니다.",
			"[게임 바] 가끔 '하스스톤을 찾을 수 없습니다'라는 메시지가 표시되는 문제를 수정했습니다.",
			"[검사] 한밤중에서 추가 보석 슬롯에 대한 표시 로직을 업데이트했습니다.",
			"[컨텍스트 메뉴] 오염 방지 전략을 완화하여 이제 Battle.net 친구를 오른쪽 클릭할 때 Ctrl 키를 눌러야 메뉴가 표시되고, 다른 경우에는 Ctrl 키가 더 이상 필요하지 않습니다.",
			"[추가 아이템 바] 한밤중의 전문 아이템을 업데이트하고, 다른 버전의 전문 아이템 목록을 분리했습니다. PROFTWW, PROFMN을 사용하여 다른 버전의 전문 아이템 목록을 사용할 수 있습니다.",
			"[추가 아이템 바] 한밤중에 누락된 일부 물약을 추가했습니다. Perseco에게 감사드립니다.",
			"[툴팁] - [진행 상황] M+ 특수 업적의 기본 활성 항목을 조정했습니다.",
			"[목적 추적기] 퀘스트 ID를 업데이트하여 이제 인식이 더 정확해집니다.",
			"[스킨] 블리자드 가방의 스킨 성능을 최적화했습니다.",
			"[스킨] 데미지 미터 스킨이 이제 창 배경을 완전히 숨기는 것을 지원합니다.",
			"[스킨] 데미지 미터 스킨이 이제 스크롤바 조정을 지원합니다.",
			"[스킨] 위젯 스킨을 최적화하여 더 많은 진행 바를 지원합니다. 감사합니다 Dack.",
			"[스킨] 위젯 스킨이 상태 바를 스킨할 때 이제 원래 색상과 가까운 색상을 사용하려고 시도합니다.",
			"[스킨] 시나리오 캠페인 스킨이 일부 타이머 바가 표시되지 않는 문제를 수정했습니다.",
			"[스킨] BigWigs 스킨을 최적화하여 BigWigs 자체 툴팁 스킨을 지원합니다.",
		},
		["ruRU"] = {
			"[Отслеживание задач] Значительно оптимизировано использование памяти.",
			"[Прогресс заданий] Оптимизирована проблема, из-за которой иконки уровней профессий отображались в виде нечитаемых символов в прогрессе.",
			"[Панель игры] Исправлена проблема, из-за которой при нажатии на значок списка друзей иногда происходило добавление друга.",
			"[Панель игры] Исправлена проблема, из-за которой иногда появлялось сообщение 'Камень возвращения не найден'.",
			"[Осмотр] Обновлена логика отображения дополнительных слотов для самоцветов в 'Полночи'.",
			"[Контекстное меню] Упрощена стратегия предотвращения ошибок Blizzard. Теперь для отображения меню при ПКМ на друга в Battle.net требуется нажать Ctrl, а в других случаях Ctrl больше не требуется.",
			"[Дополнительная панель предметов] Обновлены предметы профессий для 'Полночи', а также разделены списки предметов профессий для разных версий. Вы можете использовать PROFTWW, PROFMN для использования списков профессиональных предметов для разных версий.",
			"[Дополнительная панель предметов] Добавлены некоторые отсутствующие зелья для 'Полночи'. Спасибо Perseco.",
			"[Подсказка] - [Прогресс] Изменены настройки специальных достижений для M+, включенных по умолчанию.",
			"[Отслеживание задач] Обновлены ID заданий, теперь распознавание будет более точным.",
			"[Скины] Оптимизирована производительность скинов для сумок Blizzard.",
			"[Скины] Скин для счетчика урона теперь поддерживает полное скрытие фона окна.",
			"[Скины] Скин для счетчика урона теперь поддерживает настройку полосы прокрутки.",
			"[Скины] Оптимизировано оформление виджетов, поддерживается больше полос прогресса. Спасибо Dack.",
			"[Скины] Оформление виджетов теперь при оформлении полос здоровья пытается использовать цвета, близкие к оригиналу.",
			"[Скины] Исправлена проблема, из-за которой скин для сценариев мог привести к тому, что некоторые таймеры не отображались.",
			"[Скины] Оптимизирован скин для BigWigs, поддерживается встроенное оформление подсказок BigWigs.",
		},
	},
}
